# Topological Augmentation of Neural CDE Conditioning

This notebook tests whether persistent-homology summaries of the **frozen Phase 0 Neural CDE latent trajectory** provide useful predictive information beyond a simple non-topological trajectory-geometry control.

The Phase 0 Neural CDE is treated as the retained backbone. Phase 1 proceeds through three gates:

1. **Feasibility:** verify that H1 persistence is nontrivial, computationally practical, and not trivially identical to simple geometry.
2. **Controlled ablation:** compare a frozen-CDE condition against matched Geometry and TDA residual augmentations.
3. **Probabilistic validation:** compare validation diffusion loss, CRPS, Energy Score, and calibration under a common sampling seed.

Feature normalization is fit on the training period only. The held-out test split is not evaluated anywhere in this notebook.

## Setup

In [6]:
import os
import sys

REPO_PATH = "/kaggle/working/diffusion-portfolio"
USERNAME = "Amir-Entezari"
REPO = "diffusion-portfolio"
BRANCH = "refactor/modular-cleanup"  # Change this

repo_url = f"https://github.com/{USERNAME}/{REPO}.git"

# Clone the specified branch if the repository doesn't exist.
if not os.path.exists(os.path.join(REPO_PATH, ".git")):
    !git clone --branch {BRANCH} --single-branch {repo_url} {REPO_PATH}

else:
    # Fetch latest changes from the specified branch.
    !git -C {REPO_PATH} fetch origin {BRANCH}

    # Switch to the branch and force-sync with remote.
    !git -C {REPO_PATH} checkout -B {BRANCH} FETCH_HEAD
    !git -C {REPO_PATH} reset --hard FETCH_HEAD

os.chdir(REPO_PATH)

SRC_PATH = os.path.join(REPO_PATH, "src")

if SRC_PATH not in sys.path:
    sys.path.insert(0, SRC_PATH)

# Verify the active branch and latest commit.
!git branch --show-current
!git log -1 --oneline

print(f"Repository synced with origin/{BRANCH}.")

From https://github.com/Amir-Entezari/diffusion-portfolio
 * branch            refactor/modular-cleanup -> FETCH_HEAD
Reset branch 'refactor/modular-cleanup'
Your branch is up to date with 'origin/refactor/modular-cleanup'.
HEAD is now at e0fe9db update .gitignore file
refactor/modular-cleanup
e0fe9db (HEAD -> refactor/modular-cleanup, origin/refactor/modular-cleanup) update .gitignore file
Repository synced with origin/refactor/modular-cleanup.

In [7]:
!pip install -q -e '.[research]'

import sys

SRC_PATH = f"{REPO_PATH}/src"

if SRC_PATH not in sys.path:
    sys.path.insert(
        0,
        SRC_PATH,
    )

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for diffusion-portfolio (pyproject.toml) ... done

In [8]:
from pathlib import Path

import json
import time

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader

from diffusion_portfolio.config import load_config
from diffusion_portfolio.data import collate_return_batch
from diffusion_portfolio.models.topology import (
    trajectory_geometry_features,
    trajectory_persistence_features,
)

from diffusion_portfolio.models.diffusion.build import build_diffusion
from diffusion_portfolio.data.preparation import prepare_datasets, load_standardizer

### Tests

Run the relevant regression tests before executing the Phase 1 experiments.

In [9]:
!pytest -q \
    tests/unit/test_cde.py \
    tests/unit/test_topology.py \
    tests/unit/test_precomputed_conditioning.py \
    tests/unit/test_conditional_diffusion_model.py \
    tests/unit/test_diffusion_training.py

.........................................                                [100%]

### Restore

Restore the Phase 0 CDE checkpoint and any previously backed-up Phase 1 outputs. Missing Phase 1 artifacts are simply recomputed.

In [10]:
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

RESTORES = {
    "phase0/neural_cde_rk4x4":
        "/kaggle/working/phase0_cde",

    "phase1/features":
        "/kaggle/working/phase1_features",

    "phase1/cde_control":
        "/kaggle/working/phase1_cde",

    "phase1/geometry_control":
        "/kaggle/working/phase1_geometry",

    "phase1/tda":
        "/kaggle/working/phase1_tda",
}

try:
    artifact_path = Path(
        kagglehub.dataset_download(
            HANDLE
        )
    )

    for relative, destination in (
        RESTORES.items()
    ):
        source = (
            artifact_path
            / relative
        )

        destination = Path(
            destination
        )

        if destination.exists():
            print(
                "Already available:",
                destination,
            )

        elif source.exists():
            shutil.copytree(
                source,
                destination,
            )

            print(
                "Restored:",
                destination,
            )

        else:
            print(
                "No backup:",
                relative,
            )

except Exception as error:
    print(
        "No backups restored.",
        error,
    )

Restored: /kaggle/working/phase0_cde
Restored: /kaggle/working/phase1_features
Restored: /kaggle/working/phase1_cde
Restored: /kaggle/working/phase1_geometry
Restored: /kaggle/working/phase1_tda

## 1. Feasibility gate

For each 60-day history, the frozen Neural CDE produces a latent trajectory

\[
H(t_1),\ldots,H(t_{60}) \in \mathbb{R}^{128}.
\]

Phase 1 treats these 60 latent states as a point cloud and computes Vietoris–Rips persistent homology through \(H_1\). Each homology dimension is summarized by persistence count, mean/std/max lifetime, persistence entropy, and the three largest lifetimes.

A seven-dimensional **simple geometry control** summarizes step lengths and distances from the trajectory centroid. This control is essential: TDA must add information beyond ordinary path scale and spread, not merely correlate with them.

In [11]:
CDE_DIR = Path(
    "/kaggle/working/phase0_cde"
)

if not CDE_DIR.exists():
    raise FileNotFoundError(
        "Phase 0 CDE artifact is required before Phase 1."
    )

cfg = load_config(
    CDE_DIR / "config.yaml"
)

checkpoint = torch.load(
    CDE_DIR / "best.pt",
    map_location="cpu",
    weights_only=False,
)

model = build_diffusion(
    cfg, n_assets=len(load_standardizer(CDE_DIR / "standardizer.npz").columns)
)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

encoder = (
    model.history_encoder
    .to(device)
    .eval()
)

for parameter in encoder.parameters():
    parameter.requires_grad_(
        False
    )

datasets = prepare_datasets(
    cfg,
    standardizer_path=(
        CDE_DIR
        / "standardizer.npz"
    ),
)

print(
    "Device:",
    device,
)

print(
    "Checkpoint epoch:",
    checkpoint[
        "epoch"
    ],
)

print(
    "Validation loss:",
    checkpoint[
        "val_loss"
    ],
)

Device: cuda
Checkpoint epoch: 42
Validation loss: 1.445402071734143

In [12]:
loader = DataLoader(
    datasets.val,
    batch_size=32,
    shuffle=False,
    collate_fn=collate_return_batch,
)

batch = next(
    iter(loader)
)

history = batch[
    "history"
].to(
    device
)

with torch.no_grad():
    trajectory = (
        encoder.encode_trajectory(
            history
        )
    )

if device.type == "cuda":
    torch.cuda.synchronize()

start = time.perf_counter()

tda_features = (
    trajectory_persistence_features(
        trajectory,
        max_homology_dim=1,
        top_k=3,
    )
)

if device.type == "cuda":
    torch.cuda.synchronize()

elapsed = (
    time.perf_counter()
    - start
)

geometry_features = (
    trajectory_geometry_features(
        trajectory
    )
)

tda_np = (
    tda_features
    .detach()
    .cpu()
    .numpy()
)

geometry_np = (
    geometry_features
    .detach()
    .cpu()
    .numpy()
)

h1 = tda_np[
    :,
    8:16,
]

tda_std = tda_np.std(
    axis=0
)

nonconstant = (
    tda_std > 1e-12
)

nonconstant_indices = (
    np.flatnonzero(
        nonconstant
    )
)

correlations = np.corrcoef(
    np.column_stack(
        [
            tda_np[
                :,
                nonconstant
            ],
            geometry_np,
        ]
    ),
    rowvar=False,
)

n_tda = int(
    nonconstant.sum()
)

tda_geometry_corr = correlations[
    :n_tda,
    n_tda:,
]

h1_rows = np.flatnonzero(
    nonconstant_indices >= 8
)

max_corr = np.max(
    np.abs(
        tda_geometry_corr
    ),
    axis=1,
)

print(
    "Trajectory:",
    tuple(
        trajectory.shape
    ),
)

print(
    "Raw TDA features:",
    tuple(
        tda_features.shape
    ),
)

print(
    "Geometry features:",
    tuple(
        geometry_features.shape
    ),
)

print(
    "TDA time per sample:",
    elapsed
    / len(
        tda_features
    ),
)

print(
    "Samples with nonzero H1:",
    np.mean(
        np.any(
            np.abs(
                h1
            )
            > 1e-10,
            axis=1,
        )
    ),
)

print(
    "Constant raw TDA indices:",
    np.flatnonzero(
        ~nonconstant
    ).tolist(),
)

print(
    "Mean max |corr| with geometry:",
    float(
        max_corr.mean()
    ),
)

print(
    "H1 max |corr| with geometry:",
    max_corr[
        h1_rows
    ],
)

Trajectory: (32, 60, 128)
Raw TDA features: (32, 16)
Geometry features: (32, 7)
TDA time per sample: 0.012573004343749972
Samples with nonzero H1: 1.0
Constant raw TDA indices: [0]
Mean max |corr| with geometry: 0.5173689653617519
H1 max |corr| with geometry: [0.56539112 0.6333281  0.58756851 0.57514293 0.51452033 0.57514293
 0.27828132 0.32600599]

### Feasibility conclusion

The feasibility gate passes:

- extraction is cheap enough for one-time precomputation;
- \(H_1\) is nonzero across the probe batch and varies between samples;
- only the finite \(H_0\) bar-count feature is constant;
- TDA features show moderate, not near-perfect, correlation with the simple geometry controls.

This justifies a controlled predictive ablation, but it is **not** evidence that TDA improves forecasting.

## 2. Canonical feature precomputation

Precompute train and validation features once from the frozen seed-42 Phase 0 CDE.

The script uses the **saved Phase 0 standardizer**, obtains the canonical CDE condition through the same encoder forward path used in Phase 0, and uses the full latent trajectory only for Geometry/TDA extraction.

Geometry and TDA normalization statistics are estimated from the training split only. Constant training features are removed automatically. The test split is not materialized.

In [13]:
!PYTHONUNBUFFERED=1 python -u scripts/extract_features.py --kind topology \
    --cde-run-dir /kaggle/working/phase0_cde \
    --output-dir /kaggle/working/phase1_features \
    --batch-size 32 \
    --device cuda

Feature cache: /kaggle/working/phase1_features Dimensions: [7, 15]

In [14]:
train = np.load(
    "/kaggle/working/phase1_features/train.npz"
)

validation = np.load(
    "/kaggle/working/phase1_features/validation.npz"
)

with open(
    "/kaggle/working/phase1_features/metadata.json",
    encoding="utf-8",
) as handle:
    feature_metadata = json.load(
        handle
    )

print(
    "Train CDE:",
    train[
        "cde_condition"
    ].shape,
)

print(
    "Train geometry:",
    train[
        "geometry"
    ].shape,
)

print(
    "Train TDA:",
    train[
        "tda"
    ].shape,
)

print(
    "Validation CDE:",
    validation[
        "cde_condition"
    ].shape,
)

print(
    "Validation geometry:",
    validation[
        "geometry"
    ].shape,
)

print(
    "Validation TDA:",
    validation[
        "tda"
    ].shape,
)

print(
    "Geometry kept:",
    feature_metadata[
        "geometry_keep_indices"
    ],
)

print(
    "TDA kept:",
    feature_metadata[
        "tda_keep_indices"
    ],
)

print(
    "Train geometry max |mean|:",
    float(
        np.abs(
            train[
                "geometry"
            ].mean(
                axis=0
            )
        ).max()
    ),
)

print(
    "Train geometry max |std - 1|:",
    float(
        np.abs(
            train[
                "geometry"
            ].std(
                axis=0
            )
            - 1.0
        ).max()
    ),
)

print(
    "Train TDA max |mean|:",
    float(
        np.abs(
            train[
                "tda"
            ].mean(
                axis=0
            )
        ).max()
    ),
)

print(
    "Train TDA max |std - 1|:",
    float(
        np.abs(
            train[
                "tda"
            ].std(
                axis=0
            )
            - 1.0
        ).max()
    ),
)

Train CDE: (10516, 128)
Train geometry: (10516, 7)
Train TDA: (10516, 15)
Validation CDE: (1256, 128)
Validation geometry: (1256, 7)
Validation TDA: (1256, 15)
Geometry kept: [0, 1, 2, 3, 4, 5, 6]
TDA kept: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Train geometry max |mean|: 1.1608055849876564e-08
Train geometry max |std - 1|: 0.0
Train TDA max |mean|: 2.0314097071150172e-08
Train TDA max |std - 1|: 5.960464477539063e-08

## 3. Controlled frozen-CDE ablation

Train three otherwise matched diffusion models:

- **CDE:** cached 128-dimensional CDE condition only;
- **Geometry:** CDE condition plus a zero-initialized learned residual projection of 7 geometry features;
- **TDA:** CDE condition plus a zero-initialized learned residual projection of the retained TDA features.

The denoiser architecture and training protocol are identical. Variant-specific module construction is followed by an RNG reset inside the trainer so the three runs receive the same training corruption stream. The zero initialization ensures Geometry and TDA begin at the unaugmented CDE condition.

### 3.1 CDE control

In [15]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant cde \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --output-dir /kaggle/working/phase1_cde \
    --device cuda \
    # --resume

Epoch 001/050 | train=0.939267 | val=1.687721
Epoch 002/050 | train=0.823087 | val=1.647581
Epoch 003/050 | train=0.773741 | val=1.589099
Epoch 004/050 | train=0.767574 | val=1.587158
Epoch 005/050 | train=0.737292 | val=1.540035
Epoch 006/050 | train=0.724811 | val=1.533042
Epoch 007/050 | train=0.734020 | val=1.521530
Epoch 008/050 | train=0.710767 | val=1.513213
Epoch 009/050 | train=0.725798 | val=1.503949
Epoch 010/050 | train=0.727210 | val=1.515503
Epoch 011/050 | train=0.694505 | val=1.552644
Epoch 012/050 | train=0.684691 | val=1.509567
Epoch 013/050 | train=0.711171 | val=1.499530
Epoch 014/050 | train=0.683715 | val=1.520785
Epoch 015/050 | train=0.701504 | val=1.524159
Epoch 016/050 | train=0.698612 | val=1.531770
Epoch 017/050 | train=0.683432 | val=1.525549
Epoch 018/050 | train=0.676027 | val=1.528887
Epoch 019/050 | train=0.700511 | val=1.531802
Epoch 020/050 | train=0.666397 | val=1.536035
Epoch 021/050 | train=0.679164 | val=1.539535
Epoch 022/050 | train=0.677020 | val=1.532562
Epoch 023/050 | train=0.656789 | val=1.561874
Epoch 024/050 | train=0.675523 | val=1.560076
Epoch 025/050 | train=0.655701 | val=1.589725
Epoch 026/050 | train=0.671832 | val=1.558124
Epoch 027/050 | train=0.641745 | val=1.555289
Epoch 028/050 | train=0.669903 | val=1.640805
Epoch 029/050 | train=0.663953 | val=1.594759
Epoch 030/050 | train=0.641612 | val=1.586206
Epoch 031/050 | train=0.620975 | val=1.589367
Epoch 032/050 | train=0.619763 | val=1.611857
Epoch 033/050 | train=0.625257 | val=1.648199
Epoch 034/050 | train=0.624119 | val=1.661999
Epoch 035/050 | train=0.613326 | val=1.669017
Epoch 036/050 | train=0.621874 | val=1.660064
Epoch 037/050 | train=0.612322 | val=1.643769
Epoch 038/050 | train=0.604355 | val=1.719425
Epoch 039/050 | train=0.628927 | val=1.682462
Epoch 040/050 | train=0.625010 | val=1.730759
Epoch 041/050 | train=0.608407 | val=1.717787
Epoch 042/050 | train=0.589745 | val=1.775362
Epoch 043/050 | train=0.586982 | val=1.702731
Epoch 044/050 | train=0.587935 | val=1.717843
Epoch 045/050 | train=0.608581 | val=1.778341
Epoch 046/050 | train=0.569716 | val=1.753344
Epoch 047/050 | train=0.578818 | val=1.750683
Epoch 048/050 | train=0.604347 | val=1.782901
Epoch 049/050 | train=0.572258 | val=1.786911
Epoch 050/050 | train=0.574739 | val=1.829617
Variant: cde Best validation loss: 1.4995304562483625

### 3.2 Geometry control

In [16]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant geometry \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --output-dir /kaggle/working/phase1_geometry \
    --device cuda \
    # --resume

Epoch 001/050 | train=0.939234 | val=1.687549
Epoch 002/050 | train=0.823025 | val=1.647027
Epoch 003/050 | train=0.773627 | val=1.588739
Epoch 004/050 | train=0.767359 | val=1.586026
Epoch 005/050 | train=0.737030 | val=1.539186
Epoch 006/050 | train=0.724651 | val=1.532588
Epoch 007/050 | train=0.733694 | val=1.521005
Epoch 008/050 | train=0.710833 | val=1.511974
Epoch 009/050 | train=0.725447 | val=1.500733
Epoch 010/050 | train=0.727270 | val=1.511273
Epoch 011/050 | train=0.694685 | val=1.550781
Epoch 012/050 | train=0.685030 | val=1.505515
Epoch 013/050 | train=0.710382 | val=1.497612
Epoch 014/050 | train=0.683409 | val=1.520182
Epoch 015/050 | train=0.700524 | val=1.520570
Epoch 016/050 | train=0.697745 | val=1.533421
Epoch 017/050 | train=0.684006 | val=1.506682
Epoch 018/050 | train=0.675855 | val=1.526175
Epoch 019/050 | train=0.700088 | val=1.526893
Epoch 020/050 | train=0.665869 | val=1.536635
Epoch 021/050 | train=0.678969 | val=1.533342
Epoch 022/050 | train=0.674989 | val=1.532366
Epoch 023/050 | train=0.657124 | val=1.552873
Epoch 024/050 | train=0.675065 | val=1.564451
Epoch 025/050 | train=0.654978 | val=1.589931
Epoch 026/050 | train=0.670361 | val=1.555823
Epoch 027/050 | train=0.641463 | val=1.564890
Epoch 028/050 | train=0.669889 | val=1.642027
Epoch 029/050 | train=0.663965 | val=1.595442
Epoch 030/050 | train=0.640172 | val=1.596024
Epoch 031/050 | train=0.622209 | val=1.597602
Epoch 032/050 | train=0.619920 | val=1.614311
Epoch 033/050 | train=0.623620 | val=1.659817
Epoch 034/050 | train=0.625753 | val=1.647644
Epoch 035/050 | train=0.613183 | val=1.664251
Epoch 036/050 | train=0.620784 | val=1.644143
Epoch 037/050 | train=0.613245 | val=1.642416
Epoch 038/050 | train=0.604371 | val=1.713071
Epoch 039/050 | train=0.626515 | val=1.691202
Epoch 040/050 | train=0.624447 | val=1.732784
Epoch 041/050 | train=0.605495 | val=1.732132
Epoch 042/050 | train=0.590165 | val=1.784289
Epoch 043/050 | train=0.586605 | val=1.705318
Epoch 044/050 | train=0.585690 | val=1.751166
Epoch 045/050 | train=0.610961 | val=1.766771
Epoch 046/050 | train=0.569505 | val=1.739105
Epoch 047/050 | train=0.582143 | val=1.809050
Epoch 048/050 | train=0.602290 | val=1.809285
Epoch 049/050 | train=0.572620 | val=1.783925
Epoch 050/050 | train=0.573861 | val=1.851054
Variant: geometry Best validation loss: 1.4976124554682688

### 3.3 TDA augmentation

In [17]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant tda \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --output-dir /kaggle/working/phase1_tda \
    --device cuda \
    # --resume

Epoch 001/050 | train=0.939228 | val=1.687450
Epoch 002/050 | train=0.823017 | val=1.646933
Epoch 003/050 | train=0.773552 | val=1.588448
Epoch 004/050 | train=0.767290 | val=1.585193
Epoch 005/050 | train=0.736942 | val=1.538534
Epoch 006/050 | train=0.724603 | val=1.532073
Epoch 007/050 | train=0.733610 | val=1.520975
Epoch 008/050 | train=0.710608 | val=1.512565
Epoch 009/050 | train=0.725574 | val=1.504032
Epoch 010/050 | train=0.727020 | val=1.516586
Epoch 011/050 | train=0.694400 | val=1.557306
Epoch 012/050 | train=0.684694 | val=1.511956
Epoch 013/050 | train=0.710514 | val=1.499644
Epoch 014/050 | train=0.683460 | val=1.520281
Epoch 015/050 | train=0.700486 | val=1.525331
Epoch 016/050 | train=0.697984 | val=1.538577
Epoch 017/050 | train=0.683542 | val=1.521633
Epoch 018/050 | train=0.676149 | val=1.520938
Epoch 019/050 | train=0.701267 | val=1.527012
Epoch 020/050 | train=0.666300 | val=1.528507
Epoch 021/050 | train=0.678786 | val=1.541048
Epoch 022/050 | train=0.676311 | val=1.532741
Epoch 023/050 | train=0.655737 | val=1.557841
Epoch 024/050 | train=0.675393 | val=1.547672
Epoch 025/050 | train=0.654981 | val=1.588722
Epoch 026/050 | train=0.672042 | val=1.551171
Epoch 027/050 | train=0.641153 | val=1.570318
Epoch 028/050 | train=0.668809 | val=1.641901
Epoch 029/050 | train=0.662507 | val=1.603082
Epoch 030/050 | train=0.641028 | val=1.589304
Epoch 031/050 | train=0.621096 | val=1.599276
Epoch 032/050 | train=0.620068 | val=1.619805
Epoch 033/050 | train=0.625398 | val=1.656810
Epoch 034/050 | train=0.623669 | val=1.656608
Epoch 035/050 | train=0.614258 | val=1.670442
Epoch 036/050 | train=0.619232 | val=1.670707
Epoch 037/050 | train=0.612324 | val=1.663979
Epoch 038/050 | train=0.603314 | val=1.732270
Epoch 039/050 | train=0.625630 | val=1.702479
Epoch 040/050 | train=0.626372 | val=1.746902
Epoch 041/050 | train=0.605660 | val=1.743987
Epoch 042/050 | train=0.589900 | val=1.810850
Epoch 043/050 | train=0.586762 | val=1.704928
Epoch 044/050 | train=0.586812 | val=1.776064
Epoch 045/050 | train=0.607155 | val=1.791427
Epoch 046/050 | train=0.567984 | val=1.791475
Epoch 047/050 | train=0.578310 | val=1.823233
Epoch 048/050 | train=0.602654 | val=1.824680
Epoch 049/050 | train=0.569831 | val=1.801206
Epoch 050/050 | train=0.573990 | val=1.856006
Variant: tda Best validation loss: 1.499644420329173

### Training summary

In [18]:
training_runs = {
    "CDE": Path(
        "/kaggle/working/phase1_cde"
    ),
    "Geometry": Path(
        "/kaggle/working/phase1_geometry"
    ),
    "TDA": Path(
        "/kaggle/working/phase1_tda"
    ),
}

rows = []

for name, path in (
    training_runs.items()
):
    with (
        path / "summary.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        summary = json.load(
            handle
        )

    projection_norm = np.nan

    if name != "CDE":
        checkpoint = torch.load(
            path / "best.pt",
            map_location="cpu",
            weights_only=False,
        )

        projection_norm = float(
            checkpoint[
                "model_state_dict"
            ][
                "residual_projection.weight"
            ].norm()
        )

    rows.append(
        {
            "Variant": name,
            "Best epoch": summary[
                "best_epoch"
            ],
            "Validation loss": summary[
                "best_val_loss"
            ],
            "Parameters": summary[
                "parameter_count"
            ],
            "Residual weight norm": (
                projection_norm
            ),
        }
    )

training_results = (
    pd.DataFrame(
        rows
    )
    .set_index(
        "Variant"
    )
)

display(
    training_results
)

          Best epoch  Validation loss  Parameters  Residual weight norm
Variant
CDE               13         1.499530      826433                   NaN
Geometry          13         1.497612      827457              1.014908
TDA               13         1.499644      828481              1.158796

Saved validation-loss ranking:

\[
\text{Geometry} < \text{CDE} < \text{TDA}.
\]

Both residual projections move away from their zero initialization, confirming that the auxiliary branches are active rather than being ignored.

## 4. Validation-only probabilistic evaluation

Evaluate the best-validation checkpoint from each run with the same protocol used elsewhere in the project:

- 1,256 validation dates;
- 256 scenarios per date;
- sampling seed 12345;
- inverse transform to raw decimal excess returns;
- CRPS, Energy Score, and interval calibration.

The test split remains untouched.

### 4.1 CDE control

In [19]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant cde \
    --run-dir /kaggle/working/phase1_cde \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:22<00:00,  3.56s/it]
CRPS: 0.00856386766510697 Energy Score: 0.03528374316484095

### 4.2 Geometry control

In [20]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant geometry \
    --run-dir /kaggle/working/phase1_geometry \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:22<00:00,  3.56s/it]
CRPS: 0.008557129403985266 Energy Score: 0.035261123029387456

### 4.3 TDA augmentation

In [21]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant tda \
    --run-dir /kaggle/working/phase1_tda \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase1_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:22<00:00,  3.56s/it]
CRPS: 0.00853941466856309 Energy Score: 0.03521017080743962

### Final comparison

In [22]:
evaluation_rows = []

for name, path in (
    training_runs.items()
):
    with (
        path
        / "summary.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        train_result = json.load(
            handle
        )

    with (
        path
        / "validation_probabilistic_metrics.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        eval_result = json.load(
            handle
        )

    mean_abs_ace = float(
        np.mean(
            [
                abs(
                    item[
                        "ace"
                    ]
                )
                for item in eval_result[
                    "calibration"
                ]
            ]
        )
    )

    evaluation_rows.append(
        {
            "Variant": name,
            "Validation loss": train_result[
                "best_val_loss"
            ],
            "CRPS": eval_result[
                "crps_mean"
            ],
            "Energy Score": eval_result[
                "energy_score"
            ],
            "Mean |ACE|": (
                mean_abs_ace
            ),
        }
    )

phase1_results = (
    pd.DataFrame(
        evaluation_rows
    )
    .set_index(
        "Variant"
    )
)

display(
    phase1_results
)

          Validation loss      CRPS  Energy Score  Mean |ACE|
Variant
CDE              1.499530  0.008564      0.035284    0.183852
Geometry         1.497612  0.008557      0.035261    0.182671
TDA              1.499644  0.008539      0.035210    0.181968

## 5. Phase 1 decision

Validation results from the saved execution above:

| Variant | Validation loss ↓ | CRPS ↓ | Energy Score ↓ | Mean \(|ACE|\) ↓ |
|---|---:|---:|---:|---:|
| CDE | 1.499530 | 0.008563868 | 0.035283743 | 0.183852 |
| CDE + Geometry | **1.497612** | 0.008557129 | 0.035261123 | 0.182671 |
| CDE + TDA | 1.499644 | **0.008539415** | **0.035210171** | **0.181968** |

Geometry has the lowest validation diffusion loss. TDA has the lowest CRPS, Energy Score and mean absolute calibration error, although its diffusion loss is slightly higher than CDE's.

The evidence is mixed: the saved scenario metrics favor TDA over both controls, so the previous claim that Geometry wins all principal forecasting metrics does not apply to this execution. The improvements are small and come from one seed; they do not establish a robust predictive benefit from persistent homology.

The retained reference remains **Neural CDE-conditioned diffusion**. This comparison alone does not justify changing the retained architecture or a categorical rejection of TDA.

Previously recorded values are preserved below for historical reference; they do not match the saved execution above:

| Variant | Validation loss ↓ | CRPS ↓ | Energy Score ↓ | Mean \(|ACE|\) ↓ |
|---|---:|---:|---:|---:|
| CDE | 1.587595 | 0.008562765 | 0.035273481 | 0.170423 |
| **CDE + Geometry** | **1.584806** | **0.008539354** | **0.035193714** | 0.168234 |
| CDE + TDA | 1.586499 | 0.008562535 | 0.035281869 | **0.167544** |

The held-out test split remains untouched.

## Backup

Persist the canonical Phase 1 feature cache, controlled ablations, and validation-only evaluation artifacts to the central Kaggle dataset.

In [23]:
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

try:
    artifact_path = Path(
        kagglehub.dataset_download(
            HANDLE
        )
    )

except Exception as error:
    artifact_path = None

    print(
        "Existing backup unavailable:",
        error,
    )

staging = Path(
    "/kaggle/working/artifact_sync"
)

if staging.exists():
    shutil.rmtree(
        staging
    )

if artifact_path is not None:
    shutil.copytree(
        artifact_path,
        staging,
    )

else:
    staging.mkdir(
        parents=True,
        exist_ok=True,
    )

backups = {
    Path(
        "/kaggle/working/phase1_features"
    ): (
        staging
        / "phase1"
        / "features"
    ),

    Path(
        "/kaggle/working/phase1_cde"
    ): (
        staging
        / "phase1"
        / "cde_control"
    ),

    Path(
        "/kaggle/working/phase1_geometry"
    ): (
        staging
        / "phase1"
        / "geometry_control"
    ),

    Path(
        "/kaggle/working/phase1_tda"
    ): (
        staging
        / "phase1"
        / "tda"
    ),
}

for source, destination in (
    backups.items()
):
    if not source.exists():
        raise FileNotFoundError(
            source
        )

    if destination.exists():
        shutil.rmtree(
            destination
        )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    shutil.copytree(
        source,
        destination,
    )

    print(
        f"Prepared: {source} -> {destination}"
    )

try:
    kagglehub.dataset_upload(
        HANDLE,
        str(
            staging
        ),
        version_notes=(
            "Complete Phase 1 TDA feasibility, "
            "controlled geometry ablation, and "
            "validation-only probabilistic evaluation"
        ),
    )

    print(
        "✅ Complete Phase 1 safely backed up"
    )

except Exception as error:
    print(
        "Backup upload skipped:",
        error,
    )

Prepared: /kaggle/working/phase1_features -> /kaggle/working/artifact_sync/phase1/features
Prepared: /kaggle/working/phase1_cde -> /kaggle/working/artifact_sync/phase1/cde_control
Prepared: /kaggle/working/phase1_geometry -> /kaggle/working/artifact_sync/phase1/geometry_control
Prepared: /kaggle/working/phase1_tda -> /kaggle/working/artifact_sync/phase1/tda
Uploading Dataset https://kaggle.com/datasets/amirentezari/diffusion-portfolio ...
More than 50 files detected, creating a zip archive...
Starting upload for file /tmp/tmpuxuq_d5y/archive.zip

Uploading: 100%|██████████| 341M/341M [00:03<00:00, 110MB/s]

Upload successful: /tmp/tmpuxuq_d5y/archive.zip (326MB)

Your dataset version has been created.
Files are being processed...
See at: https://kaggle.com/datasets/amirentezari/diffusion-portfolio
✅ Complete Phase 1 safely backed up