# Conditioning and Uncertainty-Aware Routing

This notebook evaluates the Phase 0 architecture on KF12.

The experiments proceed in three stages:

1. **Phase 0A:** replace the MLP history encoder with a Neural CDE.
2. **Phase 0A robustness:** confirm the CDE improvement across paired random seeds.
3. **Phase 0B:** test whether evidential regime uncertainty provides additional value through mixture-of-experts routing.

The final Phase 0 model retains only components supported by validation results. The test split remains untouched.

## Setup

In [1]:
import os
import subprocess

REPO_PATH = "/kaggle/working/diffusion-portfolio"

REPO_URL = (
    "https://github.com/"
    "Amir-Entezari/"
    "diffusion-portfolio.git"
)

if not os.path.exists(
    os.path.join(
        REPO_PATH,
        ".git",
    )
):
    subprocess.run(
        [
            "git",
            "clone",
            REPO_URL,
            REPO_PATH,
        ],
        check=True,
    )

subprocess.run(
    [
        "git",
        "-C",
        REPO_PATH,
        "fetch",
        "origin",
        "main",
    ],
    check=True,
)

subprocess.run(
    [
        "git",
        "-C",
        REPO_PATH,
        "reset",
        "--hard",
        "origin/main",
    ],
    check=True,
)

CURRENT_COMMIT = subprocess.check_output(
    [
        "git",
        "-C",
        REPO_PATH,
        "rev-parse",
        "HEAD",
    ],
    text=True,
).strip()

os.chdir(
    REPO_PATH
)

print(
    "Synced to latest main:"
)
print(
    CURRENT_COMMIT
)

subprocess.run(
    [
        "git",
        "log",
        "-1",
        "--oneline",
    ],
    check=True,
)

Cloning into '/kaggle/working/diffusion-portfolio'...

HEAD is now at cf86f15 Make Phase 0 training safely resumable
Synced to latest main:
cf86f158948520099a343bdbd3ec8ee0ddcb7b34
cf86f15 Make Phase 0 training safely resumable

From https://github.com/Amir-Entezari/diffusion-portfolio
 * branch            main       -> FETCH_HEAD

CompletedProcess(args=['git', 'log', '-1', '--oneline'], returncode=0)

In [2]:
!pip install -q -e '.[cde]'

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.6 MB/s eta 0:00:00
  Building editable for diffusion-portfolio (pyproject.toml) ... done

### Tests

In [3]:
!pytest -q \
    tests/unit/test_cde.py \
    tests/unit/test_conditional_diffusion_model.py \
    tests/unit/test_diffusion_training.py \
    tests/unit/test_evidential.py \
    tests/unit/test_evidential_regimes.py

........................................                                 [100%]

### Restore

Restore any available previous experiment outputs. Missing backups are skipped; the corresponding experiments will run from scratch.

In [6]:
from pathlib import Path
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

RESTORES = {
    "baselines/vanilla_vpred":
        "/kaggle/working/vanilla_seed42",

    "phase0/neural_cde_rk4x4":
        "/kaggle/working/phase0_cde",

    "phase0/multiseed":
        "/kaggle/working/phase0_multiseed",

    "phase0/evidential_next_day":
        "/kaggle/working/phase0_evidential",

    "phase0/evidential_current":
        "/kaggle/working/phase0_evidential_current",

    "phase0/router":
        "/kaggle/working/phase0_router",
}

try:
    artifact_path = Path(
        kagglehub.dataset_download(
            HANDLE
        )
    )

    for relative, destination in (
        RESTORES.items()
    ):
        source = (
            artifact_path
            / relative
        )

        destination = Path(
            destination
        )

        if destination.exists():
            print(
                "Already available:",
                destination,
            )

        elif source.exists():
            shutil.copytree(
                source,
                destination,
            )

            print(
                "Restored:",
                destination,
            )

        else:
            print(
                "No backup:",
                relative,
            )

except Exception as error:
    print(
        "No backups restored."
    )
    print(
        "Experiments will run from scratch."
    )
    print(error)

Restored: /kaggle/working/vanilla_seed42
Restored: /kaggle/working/phase0_cde
Restored: /kaggle/working/phase0_multiseed
Already available: /kaggle/working/phase0_evidential
Restored: /kaggle/working/phase0_evidential_current
Restored: /kaggle/working/phase0_router

### Vanilla seed-42 reference

In [ ]:
!PYTHONUNBUFFERED=1 python -u scripts/train_diffusion.py \
    --config configs/mvp.yaml \
    --output-dir /kaggle/working/vanilla_seed42 \
    --device cuda \
    --resume

In [ ]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --run-dir /kaggle/working/vanilla_seed42 \
    --batch-size 32 \
    --device cuda

## Neural CDE Conditioning

Phase 0A tests whether replacing the Vanilla diffusion model's MLP history encoder with a Neural CDE improves probabilistic forecasting on KF12.

### Canonical seed-42 training

In [9]:
!PYTHONUNBUFFERED=1 python -u scripts/train_diffusion.py \
    --config configs/cde.yaml \
    --output-dir /kaggle/working/phase0_cde \
    --device cuda \
    --resume

========================================================================
VANILLA CONDITIONAL DIFFUSION TRAINING
========================================================================
Device: cuda
GPU: Tesla T4
Prediction type: v_prediction
History encoder: cde
Diffusion steps: 100

Loading KF12 data...
Train samples: 10516
Validation samples: 1256
Test samples: 4781
Parameters: 1,321,793

Training...
Epoch 001/050 | train=0.979311 | val=1.819148
Epoch 002/050 | train=0.844835 | val=1.786172
Epoch 003/050 | train=0.796894 | val=1.700542
Epoch 004/050 | train=0.782263 | val=1.659349
Epoch 005/050 | train=0.759299 | val=1.591604
Epoch 006/050 | train=0.739555 | val=1.595205
Epoch 007/050 | train=0.745646 | val=1.578609
Epoch 008/050 | train=0.721117 | val=1.591480
Epoch 009/050 | train=0.751829 | val=1.558710
Epoch 010/050 | train=0.747048 | val=1.559329
Epoch 011/050 | train=0.715129 | val=1.572181
Epoch 012/050 | train=0.712936 | val=1.546897
Epoch 013/050 | train=0.734503 | val=1.545789
Epoch 014/050 | train=0.710157 | val=1.541380
Epoch 015/050 | train=0.735714 | val=1.562583
Epoch 016/050 | train=0.726755 | val=1.549307
Epoch 017/050 | train=0.718143 | val=1.522650
Epoch 018/050 | train=0.705611 | val=1.511884
Epoch 019/050 | train=0.733587 | val=1.489395
Epoch 020/050 | train=0.698661 | val=1.509842
Epoch 021/050 | train=0.714688 | val=1.512198
Epoch 022/050 | train=0.710994 | val=1.497447
Epoch 023/050 | train=0.698085 | val=1.512587
Epoch 024/050 | train=0.723927 | val=1.494170
Epoch 025/050 | train=0.708449 | val=1.522239
Epoch 026/050 | train=0.720155 | val=1.499233
Epoch 027/050 | train=0.690061 | val=1.508034
Epoch 028/050 | train=0.733998 | val=1.529700
Epoch 029/050 | train=0.720031 | val=1.488057
Epoch 030/050 | train=0.706072 | val=1.534645
Epoch 031/050 | train=0.682852 | val=1.516030
Epoch 032/050 | train=0.687451 | val=1.509938
Epoch 033/050 | train=0.690933 | val=1.478917
Epoch 034/050 | train=0.693171 | val=1.467143
Epoch 035/050 | train=0.686747 | val=1.482941
Epoch 036/050 | train=0.703399 | val=1.461297
Epoch 037/050 | train=0.692398 | val=1.487721
Epoch 038/050 | train=0.691075 | val=1.500487
Epoch 039/050 | train=0.712399 | val=1.483628
Epoch 040/050 | train=0.721277 | val=1.483109
Epoch 041/050 | train=0.707288 | val=1.451119
Epoch 042/050 | train=0.691168 | val=1.445402
Epoch 043/050 | train=0.684132 | val=1.467966
Epoch 044/050 | train=0.694149 | val=1.460344
Epoch 045/050 | train=0.726744 | val=1.459896
Epoch 046/050 | train=0.681557 | val=1.504864
Epoch 047/050 | train=0.696793 | val=1.467766
Epoch 048/050 | train=0.722039 | val=1.461354
Epoch 049/050 | train=0.696925 | val=1.458728
Epoch 050/050 | train=0.705505 | val=1.470942

========================================================================
TRAINING COMPLETE
========================================================================
Best epoch: 42
Best validation loss: 1.445402071734143

Validation sampling sanity:
standardized_mean: 0.019835667684674263
standardized_std: 1.3912051916122437
standardized_max_abs: 4.6169891357421875
raw_mean: 0.0005211855168454349
raw_std: 0.013061672449111938
raw_max_abs: 0.056687500327825546

Artifacts: /kaggle/working/phase0_cde

### Validation evaluation

In [6]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --run-dir /kaggle/working/phase0_cde \
    --batch-size 32 \
    --device cuda

========================================================================
DIFFUSION VALIDATION FORECAST EVALUATION
========================================================================
Device: cuda
GPU: Tesla T4
History encoder: cde
Scenarios per date: 256
Inference batch size: 32
Sampling seed: 12345

Validation samples: 1256
Validation start: 2000-01-03 00:00:00
Validation end: 2004-12-31 00:00:00

Checkpoint epoch: 42
Checkpoint validation loss: 1.445402071734143

Generating VALIDATION scenarios...
Validation sampling: 100%|██████████████████████| 40/40 [02:37<00:00,  3.93s/it]

Saved validation scenarios: /kaggle/working/phase0_cde/validation_scenarios.npz
Scenario cube: (1256, 256, 12)
Raw scenario mean: -0.0010567344725131989
Raw scenario std: 0.013828642666339874
Raw scenario max abs: 0.1086999848484993

Computing VALIDATION probabilistic metrics...

========================================================================
VALIDATION PROBABILISTIC EVALUATION
========================================================================
CRPS mean: 0.008184307740418832
CRPS std across assets: 0.0018269477406119233
Energy Score: 0.03376962808211297

Calibration:
   level         PICP          ACE
    0.50     0.429472    -0.070528
    0.80     0.720276    -0.079724
    0.90     0.831940    -0.068060
    0.95     0.895701    -0.054299
    0.99     0.953954    -0.036046

Metrics saved: /kaggle/working/phase0_cde/validation_probabilistic_metrics.json

TEST SPLIT WAS NOT EVALUATED.

### Canonical seed-42 verification

In [17]:
import json
import pandas as pd
import torch

RUN_DIR = "/kaggle/working/phase0_cde"

summary = json.load(open(f"{RUN_DIR}/summary.json"))
history = pd.read_csv(f"{RUN_DIR}/history.csv")
checkpoint = torch.load(
    f"{RUN_DIR}/best.pt",
    map_location="cpu",
    weights_only=False,
)

print("epochs:", len(history))
print("summary best:", summary["best_epoch"], summary["best_val_loss"])
print("checkpoint:", checkpoint["epoch"], checkpoint["val_loss"])

assert len(history) == 50
assert checkpoint["epoch"] == summary["best_epoch"]
assert abs(
    checkpoint["val_loss"]
    - summary["best_val_loss"]
) < 1e-8

print("✅ checkpoint is consistent")

epochs: 50
summary best: 42 1.445402071734143
checkpoint: 42 1.445402071734143
✅ checkpoint is consistent

### Vanilla vs Neural CDE — Seed 42

In [19]:
import json
from pathlib import Path

import pandas as pd

VANILLA_42 = Path(
    "/kaggle/working/vanilla_seed42"
)

CDE_42 = Path(
    "/kaggle/working/phase0_cde"
)

with (
    VANILLA_42
    / "validation_probabilistic_metrics.json"
).open(
    encoding="utf-8"
) as f:
    vanilla = json.load(f)

with (
    VANILLA_42
    / "summary.json"
).open(
    encoding="utf-8"
) as f:
    vanilla_summary = json.load(f)

with (
    CDE_42
    / "validation_probabilistic_metrics.json"
).open(
    encoding="utf-8"
) as f:
    cde = json.load(f)

with (
    CDE_42
    / "summary.json"
).open(
    encoding="utf-8"
) as f:
    cde_summary = json.load(f)

comparison = pd.DataFrame({
    "Vanilla MLP": [
        vanilla_summary["best_val_loss"],
        vanilla["crps_mean"],
        vanilla["energy_score"],
    ],
    "Neural CDE": [
        cde_summary["best_val_loss"],
        cde["crps_mean"],
        cde["energy_score"],
    ],
}, index=[
    "Validation diffusion loss ↓",
    "CRPS ↓",
    "Energy Score ↓",
])

comparison["Change %"] = (
    (
        comparison["Neural CDE"]
        - comparison["Vanilla MLP"]
    )
    / comparison["Vanilla MLP"]
    * 100
)

comparison

                             Vanilla MLP  Neural CDE  Change %
Validation diffusion loss ↓     1.579357    1.445402 -8.481630
CRPS ↓                          0.008356    0.008184 -2.051135
Energy Score ↓                  0.034616    0.033770 -2.443752

In [20]:
vanilla_cal = pd.DataFrame(
    vanilla["calibration"]
)

cde_cal = pd.DataFrame(
    cde["calibration"]
)

calibration_comparison = pd.DataFrame({
    "Level": vanilla_cal["level"],
    "Vanilla PICP": vanilla_cal["picp"],
    "CDE PICP": cde_cal["picp"],
    "Vanilla |ACE|": vanilla_cal["ace"].abs(),
    "CDE |ACE|": cde_cal["ace"].abs(),
})

calibration_comparison

   Level  Vanilla PICP  CDE PICP  Vanilla |ACE|  CDE |ACE|
0   0.50      0.323381  0.429472       0.176619   0.070528
1   0.80      0.578357  0.720276       0.221643   0.079724
2   0.90      0.700637  0.831940       0.199363   0.068060
3   0.95      0.784833  0.895701       0.165167   0.054299
4   0.99      0.880507  0.953954       0.109493   0.036046

### Multi-Seed Robustness

The seed-42 improvement is confirmed using paired Vanilla and Neural CDE runs for seeds 42, 43, and 44 under the same validation protocol.

In [18]:
!PYTHONUNBUFFERED=1 python -u scripts/run_multiseed.py \
    --seed42-vanilla-dir /kaggle/working/vanilla_seed42 \
    --seed42-cde-dir /kaggle/working/phase0_cde \
    --output-root /kaggle/working/phase0_multiseed \
    --seeds 43 44 \
    --device cuda

========================================================================
PHASE 0A — PAIRED MULTI-SEED CONFIRMATION
========================================================================
Existing seed 42 Vanilla: /kaggle/input/datasets/amirentezari/diffusion-portfolio/baselines/vanilla_vpred
Existing seed 42 CDE: /kaggle/working/phase0_cde
New paired seeds: [43, 44]
Training already complete: vanilla seed 43
Validation evaluation already complete: vanilla seed 43

========================================================================
TRAINING CDE SEED 43
========================================================================

$ /usr/bin/python3 scripts/train_diffusion.py --config /kaggle/working/phase0_multiseed/configs/cde_seed_43.yaml --output-dir /kaggle/working/phase0_multiseed/cde/seed_43 --device cuda
========================================================================
VANILLA CONDITIONAL DIFFUSION TRAINING
========================================================================
Device: cuda
GPU: Tesla T4
Prediction type: v_prediction
History encoder: cde
Diffusion steps: 100

Loading KF12 data...
Train samples: 10516
Validation samples: 1256
Test samples: 4781
Parameters: 1,321,793

Training...
Epoch 001/050 | train=0.969969 | val=1.805655
Epoch 002/050 | train=0.858277 | val=1.740492
Epoch 003/050 | train=0.794634 | val=1.723418
Epoch 004/050 | train=0.780842 | val=1.647758
Epoch 005/050 | train=0.810054 | val=1.677510
Epoch 006/050 | train=0.776340 | val=1.618261
Epoch 007/050 | train=0.755658 | val=1.622323
Epoch 008/050 | train=0.741153 | val=1.617733
Epoch 009/050 | train=0.760858 | val=1.609471
Epoch 010/050 | train=0.741655 | val=1.587366
Epoch 011/050 | train=0.742564 | val=1.569922
Epoch 012/050 | train=0.738303 | val=1.574440
Epoch 013/050 | train=0.724803 | val=1.534467
Epoch 014/050 | train=0.728484 | val=1.562573
Epoch 015/050 | train=0.712614 | val=1.549025
Epoch 016/050 | train=0.732292 | val=1.568044
Epoch 017/050 | train=0.727612 | val=1.547499
Epoch 018/050 | train=0.706555 | val=1.526244
Epoch 019/050 | train=0.713075 | val=1.521068
Epoch 020/050 | train=0.715067 | val=1.521058
Epoch 021/050 | train=0.709262 | val=1.532836
Epoch 022/050 | train=0.733301 | val=1.501562
Epoch 023/050 | train=0.702219 | val=1.492565
Epoch 024/050 | train=0.711237 | val=1.533411
Epoch 025/050 | train=0.701768 | val=1.491578
Epoch 026/050 | train=0.725083 | val=1.529823
Epoch 027/050 | train=0.701338 | val=1.478707
Epoch 028/050 | train=0.708649 | val=1.511314
Epoch 029/050 | train=0.699546 | val=1.488040
Epoch 030/050 | train=0.693683 | val=1.502897
Epoch 031/050 | train=0.688084 | val=1.482566
Epoch 032/050 | train=0.705654 | val=1.477008
Epoch 033/050 | train=0.719953 | val=1.490868
Epoch 034/050 | train=0.732524 | val=1.483528
Epoch 035/050 | train=0.708711 | val=1.475183
Epoch 036/050 | train=0.685183 | val=1.505658
Epoch 037/050 | train=0.711000 | val=1.465092
Epoch 038/050 | train=0.708711 | val=1.483492
Epoch 039/050 | train=0.719276 | val=1.463771
Epoch 040/050 | train=0.708161 | val=1.456261
Epoch 041/050 | train=0.719766 | val=1.494558
Epoch 042/050 | train=0.692974 | val=1.462621
Epoch 043/050 | train=0.704581 | val=1.450785
Epoch 044/050 | train=0.721719 | val=1.470467
Epoch 045/050 | train=0.684593 | val=1.483801
Epoch 046/050 | train=0.727834 | val=1.475615
Epoch 047/050 | train=0.692806 | val=1.480020
Epoch 048/050 | train=0.697232 | val=1.472655
Epoch 049/050 | train=0.707498 | val=1.460575
Epoch 050/050 | train=0.711114 | val=1.462025

========================================================================
TRAINING COMPLETE
========================================================================
Best epoch: 43
Best validation loss: 1.4507850632546053

Validation sampling sanity:
standardized_mean: 0.2001047134399414
standardized_std: 1.0876859426498413
standardized_max_abs: 4.488207817077637
raw_mean: 0.002228015335276723
raw_std: 0.010246474295854568
raw_max_abs: 0.041535768657922745

Artifacts: /kaggle/working/phase0_multiseed/cde/seed_43

Evaluating validation: cde seed 43

$ /usr/bin/python3 scripts/evaluate_diffusion_validation.py --run-dir /kaggle/working/phase0_multiseed/cde/seed_43 --device cuda
========================================================================
DIFFUSION VALIDATION FORECAST EVALUATION
========================================================================
Device: cuda
GPU: Tesla T4
History encoder: cde
Scenarios per date: 256
Inference batch size: 32
Sampling seed: 12345

Validation samples: 1256
Validation start: 2000-01-03 00:00:00
Validation end: 2004-12-31 00:00:00

Checkpoint epoch: 43
Checkpoint validation loss: 1.4507850632546053

Generating VALIDATION scenarios...
Validation sampling: 100%|██████████████████████| 40/40 [02:42<00:00,  4.07s/it]

Saved validation scenarios: /kaggle/working/phase0_multiseed/cde/seed_43/validation_scenarios.npz
Scenario cube: (1256, 256, 12)
Raw scenario mean: 0.0020576806273311377
Raw scenario std: 0.010899609886109829
Raw scenario max abs: 0.0822262167930603

Computing VALIDATION probabilistic metrics...

========================================================================
VALIDATION PROBABILISTIC EVALUATION
========================================================================
CRPS mean: 0.008170120847660464
CRPS std across assets: 0.002007582398139668
Energy Score: 0.03375925083025477

Calibration:
   level         PICP          ACE
    0.50     0.377455    -0.122545
    0.80     0.657776    -0.142224
    0.90     0.781714    -0.118286
    0.95     0.854034    -0.095966
    0.99     0.932458    -0.057542

Metrics saved: /kaggle/working/phase0_multiseed/cde/seed_43/validation_probabilistic_metrics.json

TEST SPLIT WAS NOT EVALUATED.

========================================================================
TRAINING VANILLA SEED 44
========================================================================

$ /usr/bin/python3 scripts/train_diffusion.py --config /kaggle/working/phase0_multiseed/configs/vanilla_seed_44.yaml --output-dir /kaggle/working/phase0_multiseed/vanilla/seed_44 --device cuda
========================================================================
VANILLA CONDITIONAL DIFFUSION TRAINING
========================================================================
Device: cuda
GPU: Tesla T4
Prediction type: v_prediction
History encoder: mlp
Diffusion steps: 100

Loading KF12 data...
Train samples: 10516
Validation samples: 1256
Test samples: 4781
Parameters: 1,044,417

Training...
Epoch 001/050 | train=0.809800 | val=1.582258
Epoch 002/050 | train=0.728328 | val=1.591534
Epoch 003/050 | train=0.721908 | val=1.571355
Epoch 004/050 | train=0.700038 | val=1.586248
Epoch 005/050 | train=0.726774 | val=1.588351
Epoch 006/050 | train=0.713669 | val=1.573469
Epoch 007/050 | train=0.688334 | val=1.579240
Epoch 008/050 | train=0.674423 | val=1.570801
Epoch 009/050 | train=0.699375 | val=1.558378
Epoch 010/050 | train=0.662146 | val=1.602887
Epoch 011/050 | train=0.680358 | val=1.610635
Epoch 012/050 | train=0.667076 | val=1.614896
Epoch 013/050 | train=0.660236 | val=1.586908
Epoch 014/050 | train=0.639823 | val=1.609909
Epoch 015/050 | train=0.649320 | val=1.598902
Epoch 016/050 | train=0.645358 | val=1.649918
Epoch 017/050 | train=0.614777 | val=1.635800
Epoch 018/050 | train=0.623044 | val=1.627731
Epoch 019/050 | train=0.635184 | val=1.640414
Epoch 020/050 | train=0.607207 | val=1.667122
Epoch 021/050 | train=0.607159 | val=1.723728
Epoch 022/050 | train=0.604728 | val=1.708164
Epoch 023/050 | train=0.579440 | val=1.678740
Epoch 024/050 | train=0.604519 | val=1.760737
Epoch 025/050 | train=0.580155 | val=1.728031
Epoch 026/050 | train=0.583795 | val=1.784217
Epoch 027/050 | train=0.586794 | val=1.787627
Epoch 028/050 | train=0.559738 | val=1.802096
Epoch 029/050 | train=0.580405 | val=1.793979
Epoch 030/050 | train=0.543218 | val=1.837839
Epoch 031/050 | train=0.531035 | val=1.873380
Epoch 032/050 | train=0.524413 | val=1.888735
Epoch 033/050 | train=0.521917 | val=1.981335
Epoch 034/050 | train=0.539686 | val=1.936718
Epoch 035/050 | train=0.527409 | val=1.933227
Epoch 036/050 | train=0.505039 | val=1.982892
Epoch 037/050 | train=0.495587 | val=2.036366
Epoch 038/050 | train=0.484568 | val=2.045573
Epoch 039/050 | train=0.490939 | val=2.084111
Epoch 040/050 | train=0.488455 | val=2.077859
Epoch 041/050 | train=0.473720 | val=2.126505
Epoch 042/050 | train=0.483693 | val=2.196115
Epoch 043/050 | train=0.469113 | val=2.248456
Epoch 044/050 | train=0.441049 | val=2.265046
Epoch 045/050 | train=0.441780 | val=2.266700
Epoch 046/050 | train=0.428547 | val=2.335065
Epoch 047/050 | train=0.424548 | val=2.369012
Epoch 048/050 | train=0.420893 | val=2.412808
Epoch 049/050 | train=0.428668 | val=2.429296
Epoch 050/050 | train=0.408172 | val=2.449790

========================================================================
TRAINING COMPLETE
========================================================================
Best epoch: 9
Best validation loss: 1.5583779568884784

Validation sampling sanity:
standardized_mean: 0.19476832449436188
standardized_std: 0.9080851078033447
standardized_max_abs: 4.069955825805664
raw_mean: 0.002013236517086625
raw_std: 0.008616814389824867
raw_max_abs: 0.04218215122818947

Artifacts: /kaggle/working/phase0_multiseed/vanilla/seed_44

Evaluating validation: vanilla seed 44

$ /usr/bin/python3 scripts/evaluate_diffusion_validation.py --run-dir /kaggle/working/phase0_multiseed/vanilla/seed_44 --device cuda
========================================================================
DIFFUSION VALIDATION FORECAST EVALUATION
========================================================================
Device: cuda
GPU: Tesla T4
History encoder: mlp
Scenarios per date: 256
Inference batch size: 32
Sampling seed: 12345

Validation samples: 1256
Validation start: 2000-01-03 00:00:00
Validation end: 2004-12-31 00:00:00

Checkpoint epoch: 9
Checkpoint validation loss: 1.5583779568884784

Generating VALIDATION scenarios...
Validation sampling: 100%|██████████████████████| 40/40 [02:16<00:00,  3.41s/it]

Saved validation scenarios: /kaggle/working/phase0_multiseed/vanilla/seed_44/validation_scenarios.npz
Scenario cube: (1256, 256, 12)
Raw scenario mean: -0.0014064917340874672
Raw scenario std: 0.009151969105005264
Raw scenario max abs: 0.08406942337751389

Computing VALIDATION probabilistic metrics...

========================================================================
VALIDATION PROBABILISTIC EVALUATION
========================================================================
CRPS mean: 0.008373465966388348
CRPS std across assets: 0.002011703553831952
Energy Score: 0.03469912264223517

Calibration:
   level         PICP          ACE
    0.50     0.309581    -0.190419
    0.80     0.564358    -0.235642
    0.90     0.694533    -0.205467
    0.95     0.777535    -0.172465
    0.99     0.880772    -0.109228

Metrics saved: /kaggle/working/phase0_multiseed/vanilla/seed_44/validation_probabilistic_metrics.json

TEST SPLIT WAS NOT EVALUATED.

========================================================================
TRAINING CDE SEED 44
========================================================================

$ /usr/bin/python3 scripts/train_diffusion.py --config /kaggle/working/phase0_multiseed/configs/cde_seed_44.yaml --output-dir /kaggle/working/phase0_multiseed/cde/seed_44 --device cuda
========================================================================
VANILLA CONDITIONAL DIFFUSION TRAINING
========================================================================
Device: cuda
GPU: Tesla T4
Prediction type: v_prediction
History encoder: cde
Diffusion steps: 100

Loading KF12 data...
Train samples: 10516
Validation samples: 1256
Test samples: 4781
Parameters: 1,321,793

Training...
Epoch 001/050 | train=0.975538 | val=1.838932
Epoch 002/050 | train=0.861449 | val=1.763196
Epoch 003/050 | train=0.814519 | val=1.708769
Epoch 004/050 | train=0.772840 | val=1.651418
Epoch 005/050 | train=0.787728 | val=1.617410
Epoch 006/050 | train=0.769834 | val=1.626227
Epoch 007/050 | train=0.736425 | val=1.588092
Epoch 008/050 | train=0.720215 | val=1.574590
Epoch 009/050 | train=0.750974 | val=1.567008
Epoch 010/050 | train=0.715378 | val=1.589577
Epoch 011/050 | train=0.734225 | val=1.585500
Epoch 012/050 | train=0.725765 | val=1.576306
Epoch 013/050 | train=0.728119 | val=1.548465
Epoch 014/050 | train=0.711643 | val=1.557984
Epoch 015/050 | train=0.722646 | val=1.536307
Epoch 016/050 | train=0.724475 | val=1.542218
Epoch 017/050 | train=0.700387 | val=1.554047
Epoch 018/050 | train=0.709309 | val=1.521008
Epoch 019/050 | train=0.724367 | val=1.540939
Epoch 020/050 | train=0.709040 | val=1.509003
Epoch 021/050 | train=0.715255 | val=1.530295
Epoch 022/050 | train=0.712478 | val=1.520149
Epoch 023/050 | train=0.690036 | val=1.479208
Epoch 024/050 | train=0.721994 | val=1.512058
Epoch 025/050 | train=0.694505 | val=1.492501
Epoch 026/050 | train=0.723034 | val=1.507862
Epoch 027/050 | train=0.724659 | val=1.531268
Epoch 028/050 | train=0.702741 | val=1.486348
Epoch 029/050 | train=0.735022 | val=1.482014
Epoch 030/050 | train=0.701711 | val=1.499443
Epoch 031/050 | train=0.687868 | val=1.485254
Epoch 032/050 | train=0.688686 | val=1.498567
Epoch 033/050 | train=0.696713 | val=1.497300
Epoch 034/050 | train=0.729686 | val=1.509799
Epoch 035/050 | train=0.705903 | val=1.481911
Epoch 036/050 | train=0.684235 | val=1.486465
Epoch 037/050 | train=0.696560 | val=1.485052
Epoch 038/050 | train=0.680710 | val=1.499814
Epoch 039/050 | train=0.700481 | val=1.506310
Epoch 040/050 | train=0.710746 | val=1.474186
Epoch 041/050 | train=0.697722 | val=1.480292
Epoch 042/050 | train=0.735780 | val=1.492859
Epoch 043/050 | train=0.713210 | val=1.492449
Epoch 044/050 | train=0.685262 | val=1.485268
Epoch 045/050 | train=0.702459 | val=1.487263
Epoch 046/050 | train=0.684649 | val=1.486694
Epoch 047/050 | train=0.690091 | val=1.471469
Epoch 048/050 | train=0.692146 | val=1.477334
Epoch 049/050 | train=0.706648 | val=1.467280
Epoch 050/050 | train=0.707714 | val=1.470296

========================================================================
TRAINING COMPLETE
========================================================================
Best epoch: 49
Best validation loss: 1.467280057205516

Validation sampling sanity:
standardized_mean: 0.16987405717372894
standardized_std: 1.1209161281585693
standardized_max_abs: 4.0531511306762695
raw_mean: 0.0018780063837766647
raw_std: 0.010542148724198341
raw_max_abs: 0.042009174823760986

Artifacts: /kaggle/working/phase0_multiseed/cde/seed_44

Evaluating validation: cde seed 44

$ /usr/bin/python3 scripts/evaluate_diffusion_validation.py --run-dir /kaggle/working/phase0_multiseed/cde/seed_44 --device cuda
========================================================================
DIFFUSION VALIDATION FORECAST EVALUATION
========================================================================
Device: cuda
GPU: Tesla T4
History encoder: cde
Scenarios per date: 256
Inference batch size: 32
Sampling seed: 12345

Validation samples: 1256
Validation start: 2000-01-03 00:00:00
Validation end: 2004-12-31 00:00:00

Checkpoint epoch: 49
Checkpoint validation loss: 1.467280057205516

Generating VALIDATION scenarios...
Validation sampling: 100%|██████████████████████| 40/40 [02:40<00:00,  4.02s/it]

Saved validation scenarios: /kaggle/working/phase0_multiseed/cde/seed_44/validation_scenarios.npz
Scenario cube: (1256, 256, 12)
Raw scenario mean: -0.0003573615977074951
Raw scenario std: 0.009400124661624432
Raw scenario max abs: 0.0829247236251831

Computing VALIDATION probabilistic metrics...

========================================================================
VALIDATION PROBABILISTIC EVALUATION
========================================================================
CRPS mean: 0.008241341914992614
CRPS std across assets: 0.002030257499309478
Energy Score: 0.03407626384367797

Calibration:
   level         PICP          ACE
    0.50     0.332006    -0.167994
    0.80     0.593418    -0.206582
    0.90     0.712049    -0.187951
    0.95     0.796775    -0.153225
    0.99     0.893378    -0.096622

Metrics saved: /kaggle/working/phase0_multiseed/cde/seed_44/validation_probabilistic_metrics.json

TEST SPLIT WAS NOT EVALUATED.

========================================================================
PER-SEED RESULTS
========================================================================
architecture  seed  best_epoch  validation_loss     crps   energy  mean_abs_ace
         cde    42          42         1.445402 0.008184 0.033770      0.061731
     vanilla    42           3         1.579357 0.008356 0.034616      0.174457
         cde    43          43         1.450785 0.008170 0.033759      0.107313
     vanilla    43           3         1.577432 0.008284 0.034502      0.178491
         cde    44          49         1.467280 0.008241 0.034076      0.162475
     vanilla    44           9         1.558378 0.008373 0.034699      0.182644

========================================================================
PAIRED CDE - VANILLA SUMMARY
========================================================================
validation_loss: mean delta=-0.117233518, CDE wins=3/3
crps: mean delta=-0.000139229, CDE wins=3/3
energy: mean delta=-0.000737022, CDE wins=3/3
mean_abs_ace: mean delta=-0.068024593, CDE wins=3/3

Results saved to: /kaggle/working/phase0_multiseed

TEST SPLIT WAS NOT EVALUATED.

In [ ]:
import json
from pathlib import Path

import pandas as pd

MULTISEED_DIR = Path(
    "/kaggle/working/phase0_multiseed"
)

per_seed = pd.read_csv(
    MULTISEED_DIR
    / "per_seed_results.csv"
)

with (
    MULTISEED_DIR
    / "summary.json"
).open(
    encoding="utf-8"
) as f:
    multiseed_summary = json.load(f)

display(
    per_seed
)

paired = pd.DataFrame(
    multiseed_summary[
        "summary"
    ][
        "paired"
    ]
).T

display(
    paired
)

### conclusion

Neural CDE outperforms Vanilla on validation diffusion loss, CRPS, Energy Score, and mean absolute calibration error for all three paired seeds.

The Neural CDE is therefore retained as the Phase 0 conditioning backbone.

## Evidential Regime Uncertainty

Phase 0B tests whether uncertainty derived from the Neural CDE representation provides useful regime information and whether that signal improves downstream diffusion forecasting through uncertainty-aware routing.

### Phase 0B1a — Next-Day Regime Probe

In [24]:
!python scripts/train_evidential_regime.py \
    --cde-run-dir /kaggle/working/phase0_cde \
    --config configs/evidential.yaml \
    --output-dir /kaggle/working/phase0_evidential \
    --regime-target next_day \
    --device cuda

========================================================================
PHASE 0B1 — FROZEN CDE REGIME PROBES
========================================================================
Device: cuda
Frozen CDE checkpoint epoch: 42
Frozen CDE validation loss: 1.445402071734143

Extracting frozen CDE embeddings...
Train embeddings: (10516, 128)
Validation embeddings: (1256, 128)

Train-only thresholds: (0.004863632811078985, 0.008021274431265364)
Train class counts: [3505, 3506, 3505]
Validation class counts: [98, 279, 879]

Training evidential probe...
Evidential 001/050 | train=1.596359 | val_nll=1.168709 | kl=0.100
Evidential 002/050 | train=1.611986 | val_nll=1.208462 | kl=0.200
Evidential 003/050 | train=1.599471 | val_nll=1.222922 | kl=0.300
Evidential 004/050 | train=1.579625 | val_nll=1.219139 | kl=0.400
Evidential 005/050 | train=1.608150 | val_nll=1.208724 | kl=0.500
Evidential 006/050 | train=1.595672 | val_nll=1.198392 | kl=0.600
Evidential 007/050 | train=1.595911 | val_nll=1.183058 | kl=0.700
Evidential 008/050 | train=1.596618 | val_nll=1.174049 | kl=0.800
Evidential 009/050 | train=1.601604 | val_nll=1.164515 | kl=0.900
Evidential 010/050 | train=1.603075 | val_nll=1.181540 | kl=1.000
Evidential 011/050 | train=1.581237 | val_nll=1.152094 | kl=1.000
Evidential 012/050 | train=1.558420 | val_nll=1.143017 | kl=1.000
Evidential 013/050 | train=1.552095 | val_nll=1.151885 | kl=1.000
Evidential 014/050 | train=1.541997 | val_nll=1.143983 | kl=1.000
Evidential 015/050 | train=1.531145 | val_nll=1.155089 | kl=1.000
Evidential 016/050 | train=1.521419 | val_nll=1.133954 | kl=1.000
Evidential 017/050 | train=1.514898 | val_nll=1.136031 | kl=1.000
Evidential 018/050 | train=1.508312 | val_nll=1.131634 | kl=1.000
Evidential 019/050 | train=1.499620 | val_nll=1.120169 | kl=1.000
Evidential 020/050 | train=1.492035 | val_nll=1.131768 | kl=1.000
Evidential 021/050 | train=1.489272 | val_nll=1.126342 | kl=1.000
Evidential 022/050 | train=1.492379 | val_nll=1.119308 | kl=1.000
Evidential 023/050 | train=1.484113 | val_nll=1.118357 | kl=1.000
Evidential 024/050 | train=1.476614 | val_nll=1.138420 | kl=1.000
Evidential 025/050 | train=1.495447 | val_nll=1.121131 | kl=1.000
Evidential 026/050 | train=1.472783 | val_nll=1.113736 | kl=1.000
Evidential 027/050 | train=1.471657 | val_nll=1.112379 | kl=1.000
Evidential 028/050 | train=1.465485 | val_nll=1.098220 | kl=1.000
Evidential 029/050 | train=1.464906 | val_nll=1.109967 | kl=1.000
Evidential 030/050 | train=1.468770 | val_nll=1.094961 | kl=1.000
Evidential 031/050 | train=1.462692 | val_nll=1.100844 | kl=1.000
Evidential 032/050 | train=1.463040 | val_nll=1.099157 | kl=1.000
Evidential 033/050 | train=1.459288 | val_nll=1.094802 | kl=1.000
Evidential 034/050 | train=1.460737 | val_nll=1.107344 | kl=1.000
Evidential 035/050 | train=1.463806 | val_nll=1.103858 | kl=1.000
Evidential 036/050 | train=1.456504 | val_nll=1.093576 | kl=1.000
Evidential 037/050 | train=1.459929 | val_nll=1.083321 | kl=1.000
Evidential 038/050 | train=1.457055 | val_nll=1.078410 | kl=1.000
Evidential 039/050 | train=1.457038 | val_nll=1.122323 | kl=1.000
Evidential 040/050 | train=1.466380 | val_nll=1.107439 | kl=1.000
Evidential 041/050 | train=1.456854 | val_nll=1.097054 | kl=1.000
Evidential 042/050 | train=1.456859 | val_nll=1.117012 | kl=1.000
Evidential 043/050 | train=1.460075 | val_nll=1.116719 | kl=1.000
Evidential 044/050 | train=1.465430 | val_nll=1.089966 | kl=1.000
Evidential 045/050 | train=1.449309 | val_nll=1.102277 | kl=1.000
Evidential 046/050 | train=1.451940 | val_nll=1.099181 | kl=1.000
Evidential 047/050 | train=1.449407 | val_nll=1.096408 | kl=1.000
Evidential 048/050 | train=1.450836 | val_nll=1.086454 | kl=1.000
Evidential 049/050 | train=1.449047 | val_nll=1.088014 | kl=1.000
Evidential 050/050 | train=1.452514 | val_nll=1.088941 | kl=1.000

Training softmax control...
Softmax    001/050 | train=5.055666 | val_nll=5.839772
Softmax    002/050 | train=2.493427 | val_nll=4.210349
Softmax    003/050 | train=2.005600 | val_nll=3.531376
Softmax    004/050 | train=1.786844 | val_nll=3.279389
Softmax    005/050 | train=1.697664 | val_nll=2.931601
Softmax    006/050 | train=1.567645 | val_nll=2.669128
Softmax    007/050 | train=1.494376 | val_nll=2.473003
Softmax    008/050 | train=1.428213 | val_nll=2.358158
Softmax    009/050 | train=1.383819 | val_nll=2.337582
Softmax    010/050 | train=1.345963 | val_nll=2.223235
Softmax    011/050 | train=1.319226 | val_nll=1.999348
Softmax    012/050 | train=1.274034 | val_nll=1.883620
Softmax    013/050 | train=1.264446 | val_nll=1.790421
Softmax    014/050 | train=1.240701 | val_nll=1.787950
Softmax    015/050 | train=1.232666 | val_nll=1.757754
Softmax    016/050 | train=1.252607 | val_nll=1.725329
Softmax    017/050 | train=1.205207 | val_nll=1.655723
Softmax    018/050 | train=1.230812 | val_nll=1.577920
Softmax    019/050 | train=1.188244 | val_nll=1.549259
Softmax    020/050 | train=1.178896 | val_nll=1.548177
Softmax    021/050 | train=1.178629 | val_nll=1.450076
Softmax    022/050 | train=1.174768 | val_nll=1.460279
Softmax    023/050 | train=1.148269 | val_nll=1.430155
Softmax    024/050 | train=1.149068 | val_nll=1.455401
Softmax    025/050 | train=1.169969 | val_nll=1.605623
Softmax    026/050 | train=1.175023 | val_nll=1.403223
Softmax    027/050 | train=1.126426 | val_nll=1.373368
Softmax    028/050 | train=1.133812 | val_nll=1.457983
Softmax    029/050 | train=1.163532 | val_nll=1.571238
Softmax    030/050 | train=1.143584 | val_nll=1.336797
Softmax    031/050 | train=1.129413 | val_nll=1.334482
Softmax    032/050 | train=1.141078 | val_nll=1.356399
Softmax    033/050 | train=1.150466 | val_nll=1.265904
Softmax    034/050 | train=1.125245 | val_nll=1.340815
Softmax    035/050 | train=1.139358 | val_nll=1.301445
Softmax    036/050 | train=1.126091 | val_nll=1.320612
Softmax    037/050 | train=1.153253 | val_nll=1.372255
Softmax    038/050 | train=1.149327 | val_nll=1.332589
Softmax    039/050 | train=1.142024 | val_nll=1.341742
Softmax    040/050 | train=1.154885 | val_nll=1.272035
Softmax    041/050 | train=1.111061 | val_nll=1.231102
Softmax    042/050 | train=1.113649 | val_nll=1.258417
Softmax    043/050 | train=1.135973 | val_nll=1.380055
Softmax    044/050 | train=1.141075 | val_nll=1.227154
Softmax    045/050 | train=1.117492 | val_nll=1.408580
Softmax    046/050 | train=1.130690 | val_nll=1.233992
Softmax    047/050 | train=1.125333 | val_nll=1.268772
Softmax    048/050 | train=1.132265 | val_nll=1.260714
Softmax    049/050 | train=1.114149 | val_nll=1.219080
Softmax    050/050 | train=1.125062 | val_nll=1.492607

========================================================================
PHASE 0B1 VALIDATION RESULTS
========================================================================

Evidential:
  accuracy: 0.3885350227355957
  macro_f1: 0.3155046382721513
  nll: 1.0784099102020264
  brier: 0.6489302515983582
  ece: 0.06193961074967293
  mean_vacuity: 0.7190153002738953
  vacuity_correct: 0.6690405011177063
  vacuity_incorrect: 0.7507701516151428

Softmax control:
  accuracy: 0.34952229261398315
  macro_f1: 0.28910064653304374
  nll: 1.2190802097320557
  brier: 0.731661856174469
  ece: 0.15155049325649148

Artifacts: /kaggle/working/phase0_evidential

TEST SPLIT WAS NOT EVALUATED.

In [26]:
import numpy as np
import pandas as pd

path = (
    "/kaggle/working/phase0_evidential/"
    "validation_predictions.npz"
)

data = np.load(path)

labels = data["labels"]
evidential_probs = data[
    "evidential_probabilities"
]
softmax_probs = data[
    "softmax_probabilities"
]
vacuity = data[
    "evidential_vacuity"
]

evidential_pred = (
    evidential_probs.argmax(axis=1)
)

softmax_pred = (
    softmax_probs.argmax(axis=1)
)

def confusion(
    truth,
    prediction,
):
    return pd.crosstab(
        pd.Series(
            truth,
            name="True",
        ),
        pd.Series(
            prediction,
            name="Predicted",
        ),
        dropna=False,
    ).reindex(
        index=[0, 1, 2],
        columns=[0, 1, 2],
        fill_value=0,
    )

print("Evidential confusion matrix")
display(
    confusion(
        labels,
        evidential_pred,
    )
)

print("Softmax confusion matrix")
display(
    confusion(
        labels,
        softmax_pred,
    )
)

rows = []

for regime in [0, 1, 2]:
    mask = (
        labels == regime
    )

    rows.append({
        "regime": regime,
        "count": int(
            mask.sum()
        ),
        "evidential_recall": float(
            (
                evidential_pred[mask]
                == regime
            ).mean()
        ),
        "softmax_recall": float(
            (
                softmax_pred[mask]
                == regime
            ).mean()
        ),
        "mean_vacuity": float(
            vacuity[mask].mean()
        ),
    })

display(
    pd.DataFrame(rows)
)

print(
    "Always-stressed accuracy:",
    float(
        (labels == 2).mean()
    ),
)

print(
    "Evidential prediction counts:",
    np.bincount(
        evidential_pred,
        minlength=3,
    ),
)

print(
    "Softmax prediction counts:",
    np.bincount(
        softmax_pred,
        minlength=3,
    ),
)

Evidential confusion matrix

Predicted    0    1    2
True
0           35   29   34
1           84   90  105
2          248  268  363

Softmax confusion matrix

Predicted    0    1    2
True
0           23   41   34
1           85  110   84
2          274  299  306

   regime  count  evidential_recall  softmax_recall  mean_vacuity
0       0     98           0.357143        0.234694      0.752505
1       1    279           0.322581        0.394265      0.745102
2       2    879           0.412969        0.348123      0.707001

Always-stressed accuracy: 0.6998407643312102
Evidential prediction counts: [367 387 502]
Softmax prediction counts: [382 450 424]

### Phase 0B1b — Current-Regime Probe

Because next-day regime classification is strongly affected by the validation-period regime shift, the second probe targets the current regime using recent realized market behavior.

In [29]:
!python scripts/train_evidential_regime.py \
    --cde-run-dir /kaggle/working/phase0_cde \
    --config configs/evidential.yaml \
    --output-dir /kaggle/working/phase0_evidential_current \
    --regime-target current \
    --device cuda

========================================================================
PHASE 0B1 — FROZEN CDE REGIME PROBES
========================================================================
Device: cuda
Frozen CDE checkpoint epoch: 42
Frozen CDE validation loss: 1.445402071734143

Extracting frozen CDE embeddings...
Train embeddings: (10516, 128)
Validation embeddings: (1256, 128)

Train-only thresholds: (0.006870479894586817, 0.008949539408943621)
Train class counts: [3505, 3506, 3505]
Validation class counts: [9, 220, 1027]

Training evidential probe...
Evidential 001/050 | train=1.584944 | val_nll=1.181105 | kl=0.100
Evidential 002/050 | train=1.596790 | val_nll=1.284037 | kl=0.200
Evidential 003/050 | train=1.578518 | val_nll=1.235005 | kl=0.300
Evidential 004/050 | train=1.573105 | val_nll=1.257824 | kl=0.400
Evidential 005/050 | train=1.572171 | val_nll=1.224538 | kl=0.500
Evidential 006/050 | train=1.576315 | val_nll=1.215821 | kl=0.600
Evidential 007/050 | train=1.584968 | val_nll=1.208789 | kl=0.700
Evidential 008/050 | train=1.580888 | val_nll=1.186492 | kl=0.800
Evidential 009/050 | train=1.588622 | val_nll=1.189954 | kl=0.900
Evidential 010/050 | train=1.602235 | val_nll=1.168446 | kl=1.000
Evidential 011/050 | train=1.563785 | val_nll=1.167877 | kl=1.000
Evidential 012/050 | train=1.549399 | val_nll=1.143664 | kl=1.000
Evidential 013/050 | train=1.549143 | val_nll=1.148315 | kl=1.000
Evidential 014/050 | train=1.522609 | val_nll=1.145647 | kl=1.000
Evidential 015/050 | train=1.514754 | val_nll=1.144363 | kl=1.000
Evidential 016/050 | train=1.504652 | val_nll=1.136687 | kl=1.000
Evidential 017/050 | train=1.493353 | val_nll=1.140270 | kl=1.000
Evidential 018/050 | train=1.494437 | val_nll=1.142300 | kl=1.000
Evidential 019/050 | train=1.490053 | val_nll=1.113638 | kl=1.000
Evidential 020/050 | train=1.474903 | val_nll=1.102527 | kl=1.000
Evidential 021/050 | train=1.486269 | val_nll=1.118176 | kl=1.000
Evidential 022/050 | train=1.484276 | val_nll=1.085157 | kl=1.000
Evidential 023/050 | train=1.464791 | val_nll=1.091165 | kl=1.000
Evidential 024/050 | train=1.461546 | val_nll=1.105286 | kl=1.000
Evidential 025/050 | train=1.455823 | val_nll=1.100734 | kl=1.000
Evidential 026/050 | train=1.458892 | val_nll=1.111255 | kl=1.000
Evidential 027/050 | train=1.457620 | val_nll=1.098882 | kl=1.000
Evidential 028/050 | train=1.450275 | val_nll=1.074664 | kl=1.000
Evidential 029/050 | train=1.444833 | val_nll=1.088136 | kl=1.000
Evidential 030/050 | train=1.447992 | val_nll=1.079139 | kl=1.000
Evidential 031/050 | train=1.440294 | val_nll=1.077808 | kl=1.000
Evidential 032/050 | train=1.442240 | val_nll=1.096270 | kl=1.000
Evidential 033/050 | train=1.439391 | val_nll=1.086485 | kl=1.000
Evidential 034/050 | train=1.439502 | val_nll=1.106408 | kl=1.000
Evidential 035/050 | train=1.438740 | val_nll=1.071249 | kl=1.000
Evidential 036/050 | train=1.442127 | val_nll=1.050416 | kl=1.000
Evidential 037/050 | train=1.433810 | val_nll=1.060193 | kl=1.000
Evidential 038/050 | train=1.435267 | val_nll=1.080126 | kl=1.000
Evidential 039/050 | train=1.429779 | val_nll=1.030050 | kl=1.000
Evidential 040/050 | train=1.437526 | val_nll=1.105770 | kl=1.000
Evidential 041/050 | train=1.430464 | val_nll=1.046282 | kl=1.000
Evidential 042/050 | train=1.427733 | val_nll=1.055892 | kl=1.000
Evidential 043/050 | train=1.431071 | val_nll=1.064399 | kl=1.000
Evidential 044/050 | train=1.426795 | val_nll=1.089324 | kl=1.000
Evidential 045/050 | train=1.425824 | val_nll=1.073500 | kl=1.000
Evidential 046/050 | train=1.425621 | val_nll=1.082002 | kl=1.000
Evidential 047/050 | train=1.427492 | val_nll=1.066247 | kl=1.000
Evidential 048/050 | train=1.421948 | val_nll=1.050959 | kl=1.000
Evidential 049/050 | train=1.417595 | val_nll=1.050183 | kl=1.000
Evidential 050/050 | train=1.421352 | val_nll=1.074499 | kl=1.000

Training softmax control...
Softmax    001/050 | train=4.948762 | val_nll=5.977308
Softmax    002/050 | train=2.482899 | val_nll=4.330504
Softmax    003/050 | train=1.964250 | val_nll=3.624094
Softmax    004/050 | train=1.758217 | val_nll=3.374149
Softmax    005/050 | train=1.683592 | val_nll=2.985406
Softmax    006/050 | train=1.568081 | val_nll=2.758616
Softmax    007/050 | train=1.477208 | val_nll=2.670121
Softmax    008/050 | train=1.448510 | val_nll=2.370389
Softmax    009/050 | train=1.381857 | val_nll=2.383813
Softmax    010/050 | train=1.380354 | val_nll=2.209614
Softmax    011/050 | train=1.331815 | val_nll=2.021927
Softmax    012/050 | train=1.279690 | val_nll=2.006435
Softmax    013/050 | train=1.265796 | val_nll=1.966051
Softmax    014/050 | train=1.260003 | val_nll=1.771368
Softmax    015/050 | train=1.216057 | val_nll=1.687965
Softmax    016/050 | train=1.211223 | val_nll=1.758269
Softmax    017/050 | train=1.193694 | val_nll=1.691968
Softmax    018/050 | train=1.206263 | val_nll=1.663602
Softmax    019/050 | train=1.177863 | val_nll=1.635968
Softmax    020/050 | train=1.199443 | val_nll=1.509500
Softmax    021/050 | train=1.176542 | val_nll=1.592976
Softmax    022/050 | train=1.188353 | val_nll=1.563969
Softmax    023/050 | train=1.159766 | val_nll=1.471179
Softmax    024/050 | train=1.157847 | val_nll=1.460713
Softmax    025/050 | train=1.140184 | val_nll=1.511207
Softmax    026/050 | train=1.160581 | val_nll=1.505719
Softmax    027/050 | train=1.134720 | val_nll=1.336403
Softmax    028/050 | train=1.131228 | val_nll=1.371599
Softmax    029/050 | train=1.138228 | val_nll=1.689727
Softmax    030/050 | train=1.189141 | val_nll=1.356748
Softmax    031/050 | train=1.126048 | val_nll=1.358211
Softmax    032/050 | train=1.150928 | val_nll=1.335794
Softmax    033/050 | train=1.143588 | val_nll=1.339424
Softmax    034/050 | train=1.132929 | val_nll=1.459291
Softmax    035/050 | train=1.129923 | val_nll=1.373626
Softmax    036/050 | train=1.141225 | val_nll=1.337984
Softmax    037/050 | train=1.135834 | val_nll=1.504254
Softmax    038/050 | train=1.151980 | val_nll=1.393613
Softmax    039/050 | train=1.124949 | val_nll=1.381818
Softmax    040/050 | train=1.122200 | val_nll=1.262657
Softmax    041/050 | train=1.135049 | val_nll=1.283637
Softmax    042/050 | train=1.113180 | val_nll=1.347904
Softmax    043/050 | train=1.133990 | val_nll=1.349951
Softmax    044/050 | train=1.123483 | val_nll=1.354730
Softmax    045/050 | train=1.129172 | val_nll=1.307552
Softmax    046/050 | train=1.125894 | val_nll=1.470595
Softmax    047/050 | train=1.135976 | val_nll=1.330024
Softmax    048/050 | train=1.119742 | val_nll=1.261924
Softmax    049/050 | train=1.119762 | val_nll=1.282972
Softmax    050/050 | train=1.118588 | val_nll=1.385125

========================================================================
PHASE 0B1 VALIDATION RESULTS
========================================================================

Evidential:
  accuracy: 0.42754778265953064
  macro_f1: 0.28055157377513296
  nll: 1.0300495624542236
  brier: 0.6088545918464661
  ece: 0.12677206854769
  mean_vacuity: 0.6803750991821289
  vacuity_correct: 0.5854545831680298
  vacuity_incorrect: 0.7512686848640442

Softmax control:
  accuracy: 0.3957006335258484
  macro_f1: 0.26620766300821014
  nll: 1.2619236707687378
  brier: 0.7174873352050781
  ece: 0.14038318931866603

Artifacts: /kaggle/working/phase0_evidential_current

TEST SPLIT WAS NOT EVALUATED.

In [30]:
import json
import numpy as np
import pandas as pd

RUN_DIR = "/kaggle/working/phase0_evidential_current"

data = np.load(
    f"{RUN_DIR}/validation_predictions.npz"
)

with open(
    f"{RUN_DIR}/regime_thresholds.json"
) as f:
    thresholds_info = json.load(f)

scores = data["stress_scores"]
vacuity = data["evidential_vacuity"]
labels = data["labels"]

low = thresholds_info[
    "thresholds"
]["calm_normal"]

high = thresholds_info[
    "thresholds"
]["normal_stressed"]

distance_to_boundary = np.minimum(
    np.abs(scores - low),
    np.abs(scores - high),
)

correlation = np.corrcoef(
    distance_to_boundary,
    vacuity,
)[0, 1]

print(
    "Correlation(distance to boundary, vacuity):",
    correlation,
)

frame = pd.DataFrame({
    "score": scores,
    "vacuity": vacuity,
    "distance_to_boundary": distance_to_boundary,
    "label": labels,
})

frame["boundary_distance_quartile"] = pd.qcut(
    frame["distance_to_boundary"],
    q=4,
    labels=[
        "closest",
        "near",
        "far",
        "farthest",
    ],
)

display(
    frame.groupby(
        "boundary_distance_quartile",
        observed=True,
    )[
        [
            "distance_to_boundary",
            "vacuity",
        ]
    ].mean()
)

print()
print(
    "Mean vacuity closest 25%:",
    frame.loc[
        frame["boundary_distance_quartile"]
        == "closest",
        "vacuity",
    ].mean(),
)

print(
    "Mean vacuity farthest 25%:",
    frame.loc[
        frame["boundary_distance_quartile"]
        == "farthest",
        "vacuity",
    ].mean(),
)

Correlation(distance to boundary, vacuity): -0.3375002239895621

                            distance_to_boundary   vacuity
boundary_distance_quartile
closest                                 0.000569  0.770410
near                                    0.002658  0.693100
far                                     0.006006  0.655624
farthest                                0.012661  0.602368

Mean vacuity closest 25%: 0.7704095
Mean vacuity farthest 25%: 0.6023676

### Phase 0B1 conclusion

Phase 0B1 tested whether the frozen Neural CDE representation from Phase 0A contains useful regime information and whether a Dirichlet evidential head produces a meaningful uncertainty signal.

The evidential head maps the CDE representation \(H_T\) to non-negative evidence

\[
e=\operatorname{Softplus}(W H_T+b), \qquad
\alpha_k=e_k+1,
\]

with Dirichlet strength and expected class probabilities

\[
S=\sum_{k=1}^{K}\alpha_k,
\qquad
p_k=\frac{\alpha_k}{S},
\]

and evidential vacuity

\[
u=\frac{K}{S}.
\]

We initially tested prediction of the **next-day stress regime** (Phase 0B1a), but the strong train/validation regime shift made this unsuitable as the routing target.

Phase 0B1b therefore used the **current market regime**, defined from the trailing 20-day cross-sectional RMS return magnitude, with calm/normal/stressed thresholds fitted only on the training period.

The hard regime classification itself was weak under the large validation-period distribution shift (validation was ~81.8% stressed). However, the evidential model showed substantially better probabilistic behavior than an equal-capacity softmax probe:

- Evidential NLL: **1.0300** vs. Softmax **1.2619**
- Evidential Brier: **0.6089** vs. Softmax **0.7175**
- Evidential ECE: **0.1268** vs. Softmax **0.1404**

More importantly, the vacuity signal behaved meaningfully:

\[
u_{\text{incorrect}}=0.7513
>
u_{\text{correct}}=0.5855.
\]

Vacuity also increased near regime-transition boundaries:

\[
\operatorname{corr}
(\text{distance to nearest boundary},u)
=-0.338,
\]

with mean vacuity **0.7704** for the closest boundary-distance quartile versus **0.6024** for the farthest quartile.

### Conclusion

Phase 0B1 does **not** establish strong hard regime classification. However, it provides evidence that the Dirichlet head extracts a meaningful uncertainty/vacuity signal from the frozen CDE representation: uncertainty rises for incorrect predictions and near regime boundaries.

Therefore Phase 0B proceeds to **Phase 0B2: uncertainty-aware routing**. The next ablation will compare:

\[
\text{CDE}
\quad\text{vs.}\quad
\text{CDE + Softmax MoE}
\quad\text{vs.}\quad
\text{CDE + Evidential MoE}.
\]

The evidential router will use

\[
\lambda=\sigma\!\left(\gamma(u-\tau)\right),
\]

\[
G_k=(1-\lambda)p_k+\lambda\frac{1}{K},
\]

so that high evidential uncertainty moves routing weights toward uniform expert weighting. The decisive evaluation will be downstream diffusion quality—validation loss, CRPS, Energy Score, and calibration—not regime-classification accuracy alone.

### Phase 0B2 — Uncertainty-Aware Routing

In [32]:
!python scripts/train_router.py \
    --cde-run-dir /kaggle/working/phase0_cde \
    --probe-run-dir /kaggle/working/phase0_evidential_current \
    --config configs/router.yaml \
    --output-dir /kaggle/working/phase0_router \
    --device cuda

========================================================================
PHASE 0B2 — UNCERTAINTY-AWARE ROUTING
========================================================================
Device: cuda
Phase 0A checkpoint: 42 1.445402071734143

Extracting frozen CDE conditions...
Train conditions: (10516, 128)
Validation conditions: (1256, 128)

Train-only tau: 0.7766247987747192

Phase 0A val loss: 1.445402071734143
Softmax initial: 1.445402071734143
Evidential initial: 1.445402071734143

Training Softmax MoE...
Softmax initial val loss: 1.445402072
Softmax 001/030 | train=0.699422 | val=1.451107
Softmax 002/030 | train=0.703936 | val=1.450023
Softmax 003/030 | train=0.683690 | val=1.450732
Softmax 004/030 | train=0.685861 | val=1.447687
Softmax 005/030 | train=0.689584 | val=1.454488
Softmax 006/030 | train=0.688629 | val=1.446289
Softmax 007/030 | train=0.693947 | val=1.443933
Softmax 008/030 | train=0.692219 | val=1.442003
Softmax 009/030 | train=0.707080 | val=1.437889
Softmax 010/030 | train=0.667213 | val=1.445402
Softmax 011/030 | train=0.689754 | val=1.442309
Softmax 012/030 | train=0.713495 | val=1.443065
Softmax 013/030 | train=0.689681 | val=1.450168
Softmax 014/030 | train=0.699664 | val=1.447963
Softmax 015/030 | train=0.693418 | val=1.447007
Softmax 016/030 | train=0.696862 | val=1.447043
Softmax 017/030 | train=0.669291 | val=1.450347
Softmax 018/030 | train=0.705436 | val=1.448790
Softmax 019/030 | train=0.666263 | val=1.448364
Softmax 020/030 | train=0.708258 | val=1.452140
Softmax 021/030 | train=0.694858 | val=1.447846
Softmax 022/030 | train=0.705864 | val=1.447451
Softmax 023/030 | train=0.696809 | val=1.449677
Softmax 024/030 | train=0.675275 | val=1.451016
Softmax 025/030 | train=0.676358 | val=1.442865
Softmax 026/030 | train=0.713087 | val=1.446831
Softmax 027/030 | train=0.693565 | val=1.454083
Softmax 028/030 | train=0.676859 | val=1.451900
Softmax 029/030 | train=0.690159 | val=1.446965
Softmax 030/030 | train=0.674080 | val=1.450617

Training Evidential MoE...
Evidential initial val loss: 1.445402072
Evidential 001/030 | train=0.699461 | val=1.451619
Evidential 002/030 | train=0.703765 | val=1.450764
Evidential 003/030 | train=0.683488 | val=1.452127
Evidential 004/030 | train=0.685430 | val=1.449996
Evidential 005/030 | train=0.689821 | val=1.455127
Evidential 006/030 | train=0.688779 | val=1.448493
Evidential 007/030 | train=0.694127 | val=1.445136
Evidential 008/030 | train=0.692454 | val=1.444557
Evidential 009/030 | train=0.707214 | val=1.442055
Evidential 010/030 | train=0.667304 | val=1.448595
Evidential 011/030 | train=0.690039 | val=1.445454
Evidential 012/030 | train=0.712817 | val=1.448158
Evidential 013/030 | train=0.689634 | val=1.454879
Evidential 014/030 | train=0.700118 | val=1.450881
Evidential 015/030 | train=0.693801 | val=1.452973
Evidential 016/030 | train=0.697260 | val=1.453216
Evidential 017/030 | train=0.669401 | val=1.456804
Evidential 018/030 | train=0.705697 | val=1.452865
Evidential 019/030 | train=0.666241 | val=1.453500
Evidential 020/030 | train=0.707826 | val=1.455678
Evidential 021/030 | train=0.695192 | val=1.452158
Evidential 022/030 | train=0.706186 | val=1.452650
Evidential 023/030 | train=0.697364 | val=1.454233
Evidential 024/030 | train=0.675170 | val=1.457663
Evidential 025/030 | train=0.677109 | val=1.449255
Evidential 026/030 | train=0.712979 | val=1.451911
Evidential 027/030 | train=0.693456 | val=1.458317
Evidential 028/030 | train=0.677402 | val=1.455774
Evidential 029/030 | train=0.690003 | val=1.452466
Evidential 030/030 | train=0.674783 | val=1.456795

Sampling softmax_moe...
Validation sampling: 100%|██████████████████████| 40/40 [01:47<00:00,  2.69s/it]

Sampling evidential_moe...
Validation sampling: 100%|██████████████████████| 40/40 [01:47<00:00,  2.69s/it]

========================================================================
PHASE 0B2 VALIDATION COMPARISON
========================================================================
                        CDE  Softmax MoE  Evidential MoE
Validation loss ↓  1.445402     1.437889        1.442055
CRPS ↓             0.008184     0.008127        0.008134
Energy Score ↓     0.033770     0.033604        0.033628
Mean |ACE| ↓       0.061731     0.098104        0.097214

Softmax routing:
{
  "mean_weights": [
    0.33524584770202637,
    0.3018382489681244,
    0.36291590332984924
  ],
  "mean_entropy": 0.9394140839576721
}

Evidential routing:
{
  "mean_weights": [
    0.3094734251499176,
    0.301722913980484,
    0.3888036608695984
  ],
  "mean_entropy": 1.0431500673294067,
  "mean_vacuity": 0.6803741455078125,
  "mean_uniform_blend": 0.3768005967140198
}

TEST SPLIT WAS NOT EVALUATED.

### Phase 0B2 conclusion

Phase 0B2 tested whether the evidential uncertainty signal identified in Phase 0B1 improves downstream diffusion forecasting when used for mixture-of-experts routing.

For the evidential model, routing weights were

\[
\lambda=\sigma\!\left(\gamma(u-\tau)\right),
\]

\[
G_k=(1-\lambda)p_k+\lambda\frac{1}{K},
\]

where \(p_k\) are the Dirichlet expected regime probabilities, \(u=K/S\) is evidential vacuity, and \(\tau\) was set from training-period vacuity only.

The comparison was controlled:

- the validated Phase 0A CDE and diffusion denoiser were frozen;
- the Phase 0B1 regime heads were frozen;
- Softmax MoE and Evidential MoE used identical residual experts;
- experts were zero-initialized, so both models started exactly at the Phase 0A validation loss;
- only the residual experts were trained.

### Validation results

| Metric | CDE | Softmax MoE | Evidential MoE |
|---|---:|---:|---:|
| Diffusion loss ↓ | 1.445402 | **1.437889** | 1.442055 |
| CRPS ↓ | 0.008184 | **0.008127** | 0.008134 |
| Energy Score ↓ | 0.033770 | **0.033604** | 0.033628 |
| Mean \(|ACE|\) ↓ | **0.061731** | 0.098104 | 0.097214 |

Both routed variants produced small improvements in diffusion loss, CRPS, and Energy Score, but substantially worsened calibration. More importantly, the Evidential MoE did not outperform the matched Softmax MoE on loss, CRPS, or Energy Score.

The evidential mechanism itself behaved as designed: uncertainty increased routing toward uniform expert weights, with mean uniform blending of approximately **37.7%**. Therefore the negative result is not explained by an inactive uncertainty gate.

### Decision

Phase 0B1 showed that evidential vacuity is a meaningful diagnostic signal, increasing for incorrect predictions and near regime boundaries. However, Phase 0B2 does **not** show incremental downstream value from using this uncertainty for routing.

Therefore the evidential router is **not retained in the main model**. The main architecture returns to the Phase 0A Neural CDE baseline.

\[
\boxed{\text{Retain Neural CDE; reject Evidential MoE routing}}
\]

Phase 0B remains an informative ablation rather than a component of the final architecture. Further tuning of \(\tau\), \(\gamma\), or the number of experts is deferred to avoid post-hoc hyperparameter search.

Together with the paired multi-seed confirmation of Phase 0A, this closes the Phase 0 architecture-selection stage.

## Final Phase 0 Decision

Phase 0 evaluated two extensions to the Vanilla conditional diffusion baseline.

**Neural CDE conditioning is retained.** Its improvement over Vanilla is consistent across all three paired random seeds on validation diffusion loss, CRPS, Energy Score, and calibration.

**Evidential regime routing is rejected.** Although evidential vacuity behaves as a meaningful uncertainty diagnostic, the Evidential MoE does not outperform the matched Softmax MoE and both routing variants substantially worsen calibration relative to the plain Neural CDE.

The architecture carried forward to Phase 1 is therefore:

\[
\boxed{\text{Neural CDE-conditioned diffusion}}
\]

The frozen test split remains untouched.

## Backup

Persist the completed Phase 0 experiments to the central Kaggle artifact.

In [8]:
from pathlib import Path
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

try:
    artifact_path = Path(
        kagglehub.dataset_download(
            HANDLE
        )
    )

except Exception as error:
    artifact_path = None

    print(
        "Existing backup unavailable:",
        error,
    )

staging = Path(
    "/kaggle/working/artifact_sync"
)

if staging.exists():
    shutil.rmtree(
        staging
    )

if artifact_path is not None:
    shutil.copytree(
        artifact_path,
        staging,
    )

else:
    staging.mkdir(
        parents=True,
        exist_ok=True,
    )

backups = {
    Path(
        "/kaggle/working/phase0_cde"
    ): (
        staging
        / "phase0"
        / "neural_cde_rk4x4"
    ),

    Path(
        "/kaggle/working/phase0_multiseed"
    ): (
        staging
        / "phase0"
        / "multiseed"
    ),

    Path(
        "/kaggle/working/phase0_evidential"
    ): (
        staging
        / "phase0"
        / "evidential_next_day"
    ),

    Path(
        "/kaggle/working/phase0_evidential_current"
    ): (
        staging
        / "phase0"
        / "evidential_current"
    ),

    Path(
        "/kaggle/working/phase0_router"
    ): (
        staging
        / "phase0"
        / "router"
    ),
}

for source, destination in backups.items():
    if not source.exists():
        raise FileNotFoundError(
            source
        )

    if destination.exists():
        shutil.rmtree(
            destination
        )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    shutil.copytree(
        source,
        destination,
    )

    print(
        f"Prepared: {source} -> {destination}"
    )

try:
    kagglehub.dataset_upload(
        HANDLE,
        str(staging),
        version_notes=(
            "Complete Phase 0: Neural CDE, "
            "multi-seed robustness, evidential probes, "
            "and routing ablation"
        ),
    )

    print(
        "✅ Complete Phase 0 safely backed up"
    )

except Exception as error:
    print(
        "Backup upload skipped:",
        error,
    )

Prepared: /kaggle/working/phase0_cde -> /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4
Prepared: /kaggle/working/phase0_multiseed -> /kaggle/working/artifact_sync/phase0/multiseed
Prepared: /kaggle/working/phase0_evidential -> /kaggle/working/artifact_sync/phase0/evidential_next_day
Prepared: /kaggle/working/phase0_evidential_current -> /kaggle/working/artifact_sync/phase0/evidential_current
Prepared: /kaggle/working/phase0_router -> /kaggle/working/artifact_sync/phase0/router
Uploading Dataset https://kaggle.com/datasets/amirentezari/diffusion-portfolio ...
Starting upload for file /kaggle/working/artifact_sync/.artifact_store.json

Uploading: 100%|██████████| 129/129 [00:00<00:00, 177B/s]

Upload successful: /kaggle/working/artifact_sync/.artifact_store.json (129B)
Starting upload for file /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/best.pt

Uploading: 100%|██████████| 16.0M/16.0M [00:00<00:00, 17.6MB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/best.pt (15MB)
Starting upload for file /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/summary.json

Uploading: 100%|██████████| 584/584 [00:00<00:00, 836B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/summary.json (584B)
Starting upload for file /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/standardizer.npz

Uploading: 100%|██████████| 1.18k/1.18k [00:00<00:00, 1.68kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/standardizer.npz (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/history.csv

Uploading: 100%|██████████| 2.05k/2.05k [00:00<00:00, 3.01kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/config.yaml

Uploading: 100%|██████████| 1.05k/1.05k [00:01<00:00, 1.03kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/neural_cde_rk4x4/config.yaml (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/regime_thresholds.json

Uploading: 100%|██████████| 337/337 [00:00<00:00, 474B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/regime_thresholds.json (337B)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/validation_metrics.json

Uploading: 100%|██████████| 589/589 [00:00<00:00, 857B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/validation_metrics.json (589B)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/softmax_history.csv

Uploading: 100%|██████████| 2.04k/2.04k [00:00<00:00, 2.93kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/softmax_history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/evidential_history.csv

Uploading: 100%|██████████| 2.24k/2.24k [00:00<00:00, 3.11kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/evidential_history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/evidential_best.pt

Uploading: 100%|██████████| 3.62k/3.62k [00:00<00:00, 5.31kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/evidential_best.pt (4KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/validation_predictions.npz

Uploading: 100%|██████████| 66.9k/66.9k [00:00<00:00, 95.5kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/validation_predictions.npz (65KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_current/softmax_best.pt

Uploading: 100%|██████████| 3.53k/3.53k [00:00<00:00, 4.91kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_current/softmax_best.pt (3KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/best.pt

Uploading: 100%|██████████| 16.0M/16.0M [00:00<00:00, 16.0MB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/best.pt (15MB)
Starting upload for file /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/standardizer.npz

Uploading: 100%|██████████| 1.18k/1.18k [00:00<00:00, 1.72kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/standardizer.npz (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/last.pt

Uploading: 100%|██████████| 16.0M/16.0M [00:00<00:00, 21.0MB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/last.pt (15MB)
Starting upload for file /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/history.csv

Uploading: 100%|██████████| 425/425 [00:00<00:00, 641B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/history.csv (425B)
Starting upload for file /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/config.yaml

Uploading: 100%|██████████| 1.04k/1.04k [00:00<00:00, 1.51kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/multiseed/cde_seed43/config.yaml (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/config.yaml

Uploading: 100%|██████████| 287/287 [00:00<00:00, 434B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/config.yaml (287B)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/comparison.json

Uploading: 100%|██████████| 571/571 [00:00<00:00, 850B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/comparison.json (571B)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/softmax_moe/best.pt

Uploading: 100%|██████████| 403k/403k [00:00<00:00, 558kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/softmax_moe/best.pt (393KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/softmax_moe/history.csv

Uploading: 100%|██████████| 1.24k/1.24k [00:00<00:00, 1.74kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/softmax_moe/history.csv (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/softmax_moe/validation_scenarios.npz

Uploading: 100%|██████████| 15.5M/15.5M [00:00<00:00, 18.5MB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/softmax_moe/validation_scenarios.npz (15MB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/softmax_moe/validation_probabilistic_metrics.json

Uploading: 100%|██████████| 1.11k/1.11k [00:00<00:00, 1.70kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/softmax_moe/validation_probabilistic_metrics.json (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/evidential_moe/best.pt

Uploading: 100%|██████████| 403k/403k [00:00<00:00, 588kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/evidential_moe/best.pt (394KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/evidential_moe/history.csv

Uploading: 100%|██████████| 1.24k/1.24k [00:00<00:00, 1.82kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/evidential_moe/history.csv (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/evidential_moe/validation_scenarios.npz

Uploading: 100%|██████████| 15.5M/15.5M [00:00<00:00, 16.6MB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/evidential_moe/validation_scenarios.npz (15MB)
Starting upload for file /kaggle/working/artifact_sync/phase0/router/evidential_moe/validation_probabilistic_metrics.json

Uploading: 100%|██████████| 1.19k/1.19k [00:00<00:00, 1.52kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/router/evidential_moe/validation_probabilistic_metrics.json (1KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/regime_thresholds.json

Uploading: 100%|██████████| 338/338 [00:00<00:00, 474B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/regime_thresholds.json (338B)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/validation_metrics.json

Uploading: 100%|██████████| 590/590 [00:00<00:00, 833B/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/validation_metrics.json (590B)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/softmax_history.csv

Uploading: 100%|██████████| 2.03k/2.03k [00:00<00:00, 3.07kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/softmax_history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/evidential_history.csv

Uploading: 100%|██████████| 2.25k/2.25k [00:00<00:00, 3.20kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/evidential_history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/evidential_best.pt

Uploading: 100%|██████████| 3.62k/3.62k [00:00<00:00, 5.50kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/evidential_best.pt (4KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/validation_predictions.npz

Uploading: 100%|██████████| 66.9k/66.9k [00:00<00:00, 98.8kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/validation_predictions.npz (65KB)
Starting upload for file /kaggle/working/artifact_sync/phase0/evidential_next_day/softmax_best.pt

Uploading: 100%|██████████| 3.53k/3.53k [00:00<00:00, 4.98kB/s]

Upload successful: /kaggle/working/artifact_sync/phase0/evidential_next_day/softmax_best.pt (3KB)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/best.pt

Uploading: 100%|██████████| 12.6M/12.6M [00:00<00:00, 15.4MB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/best.pt (12MB)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/summary.json

Uploading: 100%|██████████| 578/578 [00:00<00:00, 860B/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/summary.json (578B)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/artifact_meta.json

Uploading: 100%|██████████| 163/163 [00:00<00:00, 239B/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/artifact_meta.json (163B)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/standardizer.npz

Uploading: 100%|██████████| 1.18k/1.18k [00:00<00:00, 1.72kB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/standardizer.npz (1KB)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/history.csv

Uploading: 100%|██████████| 2.06k/2.06k [00:00<00:00, 2.94kB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/history.csv (2KB)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/config.yaml

Uploading: 100%|██████████| 817/817 [00:00<00:00, 1.16kB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/config.yaml (817B)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/validation_scenarios.npz

Uploading: 100%|██████████| 15.5M/15.5M [00:00<00:00, 17.8MB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/validation_scenarios.npz (15MB)
Starting upload for file /kaggle/working/artifact_sync/baselines/vanilla_vpred/validation_probabilistic_metrics.json

Uploading: 100%|██████████| 1.47k/1.47k [00:00<00:00, 2.04kB/s]

Upload successful: /kaggle/working/artifact_sync/baselines/vanilla_vpred/validation_probabilistic_metrics.json (1KB)

Backup upload skipped: 403 Client Error: Forbidden for url: https://api.kaggle.com/v1/datasets.DatasetApiService/CreateDatasetVersion