# Covariance and Log-Euclidean SPD Conditioning

This notebook tests whether explicitly representing the recent covariance state improves the retained **Neural CDE-conditioned diffusion** model, and whether a manifold-aware Log-Euclidean representation adds value beyond an ordinary covariance control.

For each 60-day raw excess-return history \(X\in\mathbb{R}^{60\times12}\), Phase 2A constructs a regularized sample covariance matrix

\[
\Sigma=\frac{1}{T-1}(X-\bar X)^\top(X-\bar X),
\]

then compares two matched 78-dimensional symmetric-matrix representations:

1. **Covariance control:** \(\operatorname{svec}(\Sigma)\)
2. **Log-SPD:** \(\operatorname{svec}(\log\Sigma)\)

Both are added to the frozen Phase-0 CDE condition through the same zero-initialized residual projection. The key scientific question is not merely whether covariance helps, but whether **Log-SPD improves over ordinary covariance**.

All feature normalization is fitted on the training period only. The held-out test split is not evaluated.

## Setup

In [ ]:
import os
import sys

REPO_PATH = "/kaggle/working/diffusion-portfolio"
USERNAME = "Amir-Entezari"
REPO = "diffusion-portfolio"
BRANCH = "main"

repo_url = f"https://github.com/{USERNAME}/{REPO}.git"

# Clone the specified branch if the repository doesn't exist.
if not os.path.exists(os.path.join(REPO_PATH, ".git")):
    !git clone --branch {BRANCH} --single-branch {repo_url} {REPO_PATH}

else:
    # Fetch latest changes from the specified branch.
    !git -C {REPO_PATH} fetch origin {BRANCH}

    # Switch to the branch and force-sync with remote.
    !git -C {REPO_PATH} checkout -B {BRANCH} FETCH_HEAD
    !git -C {REPO_PATH} reset --hard FETCH_HEAD

os.chdir(REPO_PATH)

SRC_PATH = os.path.join(REPO_PATH, "src")

if SRC_PATH not in sys.path:
    sys.path.insert(0, SRC_PATH)

# Verify the active branch and latest commit.
!git branch --show-current
!git log -1 --oneline

print(f"Repository synced with origin/{BRANCH}.")

Cloning into '/kaggle/working/diffusion-portfolio'...
remote: Enumerating objects: 1133, done.
remote: Counting objects: 100% (547/547), done.
remote: Compressing objects: 100% (361/361), done.
remote: Total 1133 (delta 257), reused 408 (delta 154), pack-reused 586 (from 1)
Receiving objects: 100% (1133/1133), 1.28 MiB | 15.44 MiB/s, done.
Resolving deltas: 100% (520/520), done.
refactor/modular-cleanup
e0fe9db (HEAD -> refactor/modular-cleanup, origin/refactor/modular-cleanup) update .gitignore file
Repository synced with origin/refactor/modular-cleanup.

In [2]:
!pip install -q -e '.[research]'

import sys

SRC_PATH = f"{REPO_PATH}/src"

if SRC_PATH not in sys.path:
    sys.path.insert(
        0,
        SRC_PATH,
    )

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 44.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.8 MB/s eta 0:00:00
  Building editable for diffusion-portfolio (pyproject.toml) ... done

### Tests

Run the relevant feature, conditioning, diffusion, and training regression tests before executing Phase 2A.

In [3]:
!pytest -q \
    tests/unit/test_spd_features.py \
    tests/unit/test_precomputed_conditioning.py \
    tests/unit/test_conditional_diffusion_model.py \
    tests/unit/test_diffusion_training.py

.................................                                        [100%]

### Restore

Restore the retained Phase-0 CDE artifact and any available Phase-2A outputs. Missing Phase-2A backups are recomputed or resumed.

In [4]:
from pathlib import Path
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

SOURCE = "phase0/neural_cde_rk4x4"

DESTINATION = Path(
    "/kaggle/working/phase0_cde"
)

required = [
    "config.yaml",
    "standardizer.npz",
    "best.pt",
]

if DESTINATION.exists():
    print(
        "Already available:",
        DESTINATION,
    )

else:
    DESTINATION.mkdir(
        parents=True,
        exist_ok=True,
    )

    for filename in required:
        downloaded = Path(
            kagglehub.dataset_download(
                HANDLE,
                path=(
                    f"{SOURCE}/{filename}"
                ),
            )
        )

        shutil.copy2(
            downloaded,
            DESTINATION / filename,
        )

        print(
            "Restored:",
            filename,
        )

for filename in required:
    path = (
        DESTINATION
        / filename
    )

    if not path.exists():
        raise FileNotFoundError(
            path
        )

print(
    "Phase 0 CDE artifact is ready."
)

Restored: config.yaml
Restored: standardizer.npz
Restored: best.pt
Phase 0 CDE artifact is ready.

## 1. SPD feature feasibility

The covariance matrices are computed from **raw historical excess returns**, not standardized CDE inputs. A small relative eigenvalue floor guarantees strict positive definiteness before applying the matrix logarithm.

The symmetric matrices are represented using `svec`, where off-diagonal terms are scaled by \(\sqrt{2}\). This preserves Frobenius geometry under Euclidean vectorization and yields

\[
\frac{12(12+1)}{2}=78
\]

features for both Covariance and Log-SPD.

Before training, we verify feature dimensionality, finite values, train-only standardization, absence of degenerate columns, and the empirical covariance spectrum.

In [5]:
!PYTHONUNBUFFERED=1 python -u scripts/extract_features.py --kind spd \
    --cde-run-dir /kaggle/working/phase0_cde \
    --output-dir /kaggle/working/phase2_features \
    --batch-size 128 \
    --eigenvalue-floor 1e-6 \
    --device cuda

Feature cache: /kaggle/working/phase2_features Dimensions: [78, 78]

In [6]:
import json
import numpy as np

train = np.load(
    "/kaggle/working/phase2_features/train.npz"
)

validation = np.load(
    "/kaggle/working/phase2_features/validation.npz"
)

with open(
    "/kaggle/working/phase2_features/metadata.json",
    encoding="utf-8",
) as handle:
    feature_metadata = json.load(
        handle
    )

print(
    "Train CDE:",
    train[
        "cde_condition"
    ].shape,
)

print(
    "Train covariance:",
    train[
        "covariance"
    ].shape,
)

print(
    "Train Log-SPD:",
    train[
        "log_spd"
    ].shape,
)

print(
    "Validation covariance:",
    validation[
        "covariance"
    ].shape,
)

print(
    "Validation Log-SPD:",
    validation[
        "log_spd"
    ].shape,
)

print()
print(
    "Covariance constant indices:",
    feature_metadata[
        "covariance_constant_indices"
    ],
)

print(
    "Log-SPD constant indices:",
    feature_metadata[
        "log_spd_constant_indices"
    ],
)

print()
print(
    "Covariance train max |mean|:",
    float(
        np.abs(
            train[
                "covariance"
            ].mean(
                axis=0
            )
        ).max()
    ),
)

print(
    "Covariance train max |std - 1|:",
    float(
        np.abs(
            train[
                "covariance"
            ].std(
                axis=0
            )
            - 1.0
        ).max()
    ),
)

print(
    "Log-SPD train max |mean|:",
    float(
        np.abs(
            train[
                "log_spd"
            ].mean(
                axis=0
            )
        ).max()
    ),
)

print(
    "Log-SPD train max |std - 1|:",
    float(
        np.abs(
            train[
                "log_spd"
            ].std(
                axis=0
            )
            - 1.0
        ).max()
    ),
)

print()
print(
    "Train spectrum:",
    feature_metadata[
        "train_spectrum"
    ],
)

print(
    "Validation spectrum:",
    feature_metadata[
        "validation_spectrum"
    ],
)

Train CDE: (10516, 128)
Train covariance: (10516, 78)
Train Log-SPD: (10516, 78)
Validation covariance: (1256, 78)
Validation Log-SPD: (1256, 78)

Covariance constant indices: []
Log-SPD constant indices: []

Covariance train max |mean|: 5.074528530712996e-07
Covariance train max |std - 1|: 2.562999725341797e-06
Log-SPD train max |mean|: 7.187727533164434e-07
Log-SPD train max |std - 1|: 2.1457672119140625e-06

Train spectrum: {'min_eigenvalue_min': 8.714945920473838e-07, 'min_eigenvalue_median': 2.5683925741759595e-06, 'max_eigenvalue_median': 0.0005576540715992451, 'condition_number_median': 224.7659454345703, 'condition_number_p95': 573.766357421875, 'condition_number_max': 2489.1533203125}
Validation spectrum: {'min_eigenvalue_min': 2.3346690340986243e-06, 'min_eigenvalue_median': 9.305320418206975e-06, 'max_eigenvalue_median': 0.0013601714745163918, 'condition_number_median': 182.4652099609375, 'condition_number_p95': 409.4076232910156, 'condition_number_max': 543.7298583984375}

### Feasibility conclusion

The feature gate passes in the saved execution:

- Covariance and Log-SPD are both 78-dimensional;
- no feature is constant on the training period;
- standardized training means are approximately zero and standard deviations approximately one;
- all regularized covariance eigenvalues are positive;
- condition numbers remain finite and numerically manageable.

Passing this gate establishes numerical validity only. It does **not** establish predictive value.

## 2. Controlled frozen-CDE ablation

Train three otherwise matched models:

- **CDE:** cached 128-dimensional CDE condition only;
- **Covariance:** CDE plus a 78-D ordinary covariance representation;
- **Log-SPD:** CDE plus a 78-D Log-Euclidean SPD representation.

Covariance and Log-SPD therefore have identical auxiliary dimensionality and identical residual-projection capacity. The residual projections are zero-initialized, and the trainer resets RNG after variant-specific module construction so all variants receive the same subsequent stochastic training stream.

The test split remains untouched.

### 2.1 CDE control

In [7]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant cde \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --output-dir /kaggle/working/phase2_cde \
    --device cuda \
    --resume

Epoch 001/050 | train=0.939270 | val=1.687730
Epoch 002/050 | train=0.823088 | val=1.647606
Epoch 003/050 | train=0.773733 | val=1.589034
Epoch 004/050 | train=0.767575 | val=1.587214
Epoch 005/050 | train=0.737281 | val=1.539753
Epoch 006/050 | train=0.724784 | val=1.533307
Epoch 007/050 | train=0.733879 | val=1.521528
Epoch 008/050 | train=0.710966 | val=1.512780
Epoch 009/050 | train=0.725677 | val=1.503429
Epoch 010/050 | train=0.727439 | val=1.512881
Epoch 011/050 | train=0.694738 | val=1.551833
Epoch 012/050 | train=0.685202 | val=1.507812
Epoch 013/050 | train=0.710606 | val=1.501326
Epoch 014/050 | train=0.683745 | val=1.512928
Epoch 015/050 | train=0.700459 | val=1.521504
Epoch 016/050 | train=0.698157 | val=1.532930
Epoch 017/050 | train=0.683250 | val=1.520206
Epoch 018/050 | train=0.676700 | val=1.521364
Epoch 019/050 | train=0.700353 | val=1.538297
Epoch 020/050 | train=0.667223 | val=1.533525
Epoch 021/050 | train=0.679043 | val=1.538210
Epoch 022/050 | train=0.677097 | val=1.534138
Epoch 023/050 | train=0.656529 | val=1.551204
Epoch 024/050 | train=0.675269 | val=1.567157
Epoch 025/050 | train=0.655024 | val=1.577981
Epoch 026/050 | train=0.671225 | val=1.556242
Epoch 027/050 | train=0.641606 | val=1.558589
Epoch 028/050 | train=0.670692 | val=1.635289
Epoch 029/050 | train=0.665064 | val=1.589465
Epoch 030/050 | train=0.642676 | val=1.590888
Epoch 031/050 | train=0.620322 | val=1.582830
Epoch 032/050 | train=0.618564 | val=1.601276
Epoch 033/050 | train=0.624422 | val=1.635444
Epoch 034/050 | train=0.625296 | val=1.645606
Epoch 035/050 | train=0.613506 | val=1.645504
Epoch 036/050 | train=0.618423 | val=1.652963
Epoch 037/050 | train=0.612020 | val=1.639585
Epoch 038/050 | train=0.603617 | val=1.694797
Epoch 039/050 | train=0.627789 | val=1.670584
Epoch 040/050 | train=0.628330 | val=1.702912
Epoch 041/050 | train=0.605411 | val=1.711403
Epoch 042/050 | train=0.589838 | val=1.799829
Epoch 043/050 | train=0.585959 | val=1.711933
Epoch 044/050 | train=0.586783 | val=1.742080
Epoch 045/050 | train=0.608425 | val=1.743797
Epoch 046/050 | train=0.568937 | val=1.758126
Epoch 047/050 | train=0.580784 | val=1.789818
Epoch 048/050 | train=0.602872 | val=1.787581
Epoch 049/050 | train=0.570880 | val=1.788999
Epoch 050/050 | train=0.574868 | val=1.834969
Variant: cde Best validation loss: 1.5013259702427373

### 2.2 Ordinary covariance control

In [8]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant covariance \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --output-dir /kaggle/working/phase2_covariance \
    --device cuda \
    --resume

Epoch 001/050 | train=0.939176 | val=1.686703
Epoch 002/050 | train=0.822845 | val=1.645665
Epoch 003/050 | train=0.772882 | val=1.586804
Epoch 004/050 | train=0.766305 | val=1.580200
Epoch 005/050 | train=0.735856 | val=1.535299
Epoch 006/050 | train=0.724298 | val=1.531552
Epoch 007/050 | train=0.733094 | val=1.518538
Epoch 008/050 | train=0.709880 | val=1.509557
Epoch 009/050 | train=0.724481 | val=1.500185
Epoch 010/050 | train=0.727324 | val=1.513947
Epoch 011/050 | train=0.694477 | val=1.541108
Epoch 012/050 | train=0.683814 | val=1.500982
Epoch 013/050 | train=0.709383 | val=1.492267
Epoch 014/050 | train=0.682956 | val=1.520015
Epoch 015/050 | train=0.699821 | val=1.515728
Epoch 016/050 | train=0.697358 | val=1.523181
Epoch 017/050 | train=0.683127 | val=1.515432
Epoch 018/050 | train=0.674781 | val=1.519495
Epoch 019/050 | train=0.699858 | val=1.529796
Epoch 020/050 | train=0.666706 | val=1.533372
Epoch 021/050 | train=0.678206 | val=1.538396
Epoch 022/050 | train=0.675472 | val=1.539988
Epoch 023/050 | train=0.656428 | val=1.550141
Epoch 024/050 | train=0.676429 | val=1.544690
Epoch 025/050 | train=0.656643 | val=1.592951
Epoch 026/050 | train=0.670852 | val=1.565484
Epoch 027/050 | train=0.640613 | val=1.578266
Epoch 028/050 | train=0.668505 | val=1.625296
Epoch 029/050 | train=0.664681 | val=1.580976
Epoch 030/050 | train=0.639312 | val=1.592343
Epoch 031/050 | train=0.618512 | val=1.582656
Epoch 032/050 | train=0.619030 | val=1.591467
Epoch 033/050 | train=0.621845 | val=1.652554
Epoch 034/050 | train=0.622929 | val=1.667364
Epoch 035/050 | train=0.614046 | val=1.687698
Epoch 036/050 | train=0.617896 | val=1.652466
Epoch 037/050 | train=0.608880 | val=1.643039
Epoch 038/050 | train=0.604057 | val=1.695707
Epoch 039/050 | train=0.626155 | val=1.691896
Epoch 040/050 | train=0.625841 | val=1.719696
Epoch 041/050 | train=0.605920 | val=1.736576
Epoch 042/050 | train=0.588685 | val=1.798191
Epoch 043/050 | train=0.584813 | val=1.712645
Epoch 044/050 | train=0.586412 | val=1.745793
Epoch 045/050 | train=0.609025 | val=1.790002
Epoch 046/050 | train=0.568094 | val=1.740177
Epoch 047/050 | train=0.576535 | val=1.791139
Epoch 048/050 | train=0.603644 | val=1.798981
Epoch 049/050 | train=0.570272 | val=1.798466
Epoch 050/050 | train=0.571651 | val=1.823033
Variant: covariance Best validation loss: 1.4922669875394008

### 2.3 Log-Euclidean SPD

In [9]:
!PYTHONUNBUFFERED=1 python -u scripts/train_feature_ablation.py \
    --variant log_spd \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --output-dir /kaggle/working/phase2_log_spd \
    --device cuda \
    --resume

Epoch 001/050 | train=0.939192 | val=1.687370
Epoch 002/050 | train=0.822854 | val=1.646660
Epoch 003/050 | train=0.773314 | val=1.587910
Epoch 004/050 | train=0.766943 | val=1.584444
Epoch 005/050 | train=0.736256 | val=1.537077
Epoch 006/050 | train=0.724052 | val=1.532222
Epoch 007/050 | train=0.732734 | val=1.520844
Epoch 008/050 | train=0.709502 | val=1.514615
Epoch 009/050 | train=0.724415 | val=1.502944
Epoch 010/050 | train=0.726164 | val=1.513551
Epoch 011/050 | train=0.692820 | val=1.552883
Epoch 012/050 | train=0.683945 | val=1.505271
Epoch 013/050 | train=0.709749 | val=1.499124
Epoch 014/050 | train=0.682382 | val=1.518082
Epoch 015/050 | train=0.698448 | val=1.519104
Epoch 016/050 | train=0.696384 | val=1.528964
Epoch 017/050 | train=0.680756 | val=1.523556
Epoch 018/050 | train=0.672582 | val=1.526184
Epoch 019/050 | train=0.698529 | val=1.514984
Epoch 020/050 | train=0.663583 | val=1.523385
Epoch 021/050 | train=0.676863 | val=1.533795
Epoch 022/050 | train=0.674807 | val=1.531483
Epoch 023/050 | train=0.653961 | val=1.546365
Epoch 024/050 | train=0.671599 | val=1.566420
Epoch 025/050 | train=0.650933 | val=1.580378
Epoch 026/050 | train=0.669127 | val=1.555191
Epoch 027/050 | train=0.636286 | val=1.571893
Epoch 028/050 | train=0.664027 | val=1.625262
Epoch 029/050 | train=0.661072 | val=1.588839
Epoch 030/050 | train=0.636707 | val=1.593826
Epoch 031/050 | train=0.614816 | val=1.584819
Epoch 032/050 | train=0.616058 | val=1.596909
Epoch 033/050 | train=0.619999 | val=1.654919
Epoch 034/050 | train=0.620280 | val=1.654962
Epoch 035/050 | train=0.610643 | val=1.700525
Epoch 036/050 | train=0.616235 | val=1.650037
Epoch 037/050 | train=0.608930 | val=1.652525
Epoch 038/050 | train=0.600824 | val=1.699977
Epoch 039/050 | train=0.623103 | val=1.683865
Epoch 040/050 | train=0.622711 | val=1.723633
Epoch 041/050 | train=0.602229 | val=1.729594
Epoch 042/050 | train=0.587315 | val=1.785383
Epoch 043/050 | train=0.583550 | val=1.722010
Epoch 044/050 | train=0.582897 | val=1.720720
Epoch 045/050 | train=0.603088 | val=1.783468
Epoch 046/050 | train=0.565815 | val=1.738921
Epoch 047/050 | train=0.573539 | val=1.780241
Epoch 048/050 | train=0.597848 | val=1.796313
Epoch 049/050 | train=0.565849 | val=1.747675
Epoch 050/050 | train=0.568092 | val=1.847114
Variant: log_spd Best validation loss: 1.499124293114729

### Training summary

In [10]:
import json
import numpy as np
import pandas as pd
import torch
from pathlib import Path

runs = {
    "CDE": Path(
        "/kaggle/working/phase2_cde"
    ),
    "Covariance": Path(
        "/kaggle/working/phase2_covariance"
    ),
    "Log-SPD": Path(
        "/kaggle/working/phase2_log_spd"
    ),
}

rows = []

for name, path in (
    runs.items()
):
    with (
        path / "summary.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        result = json.load(
            handle
        )

    projection_norm = np.nan

    if name != "CDE":
        checkpoint = torch.load(
            path / "best.pt",
            map_location="cpu",
            weights_only=False,
        )

        projection_norm = float(
            checkpoint[
                "model_state_dict"
            ][
                "residual_projection.weight"
            ].norm()
        )

    rows.append(
        {
            "Variant": name,
            "Best epoch": result[
                "best_epoch"
            ],
            "Validation loss": result[
                "best_val_loss"
            ],
            "Extra dim": result[
                "extra_dim"
            ],
            "Parameters": result[
                "parameter_count"
            ],
            "Residual weight norm": (
                projection_norm
            ),
        }
    )

training_results = (
    pd.DataFrame(
        rows
    )
    .set_index(
        "Variant"
    )
)

display(
    training_results
)

,Best epoch,Validation loss,Extra dim,Parameters,Residual weight norm
Variant,,,,,
CDE,13,1.501326,0,826433,NaN
Covariance,13,1.492267,78,836545,1.704457
Log-SPD,13,1.499124,78,836545,2.518624

Training loss is only an intermediate diagnostic. The Phase-2A decision is based primarily on the validation probabilistic metrics below. In particular, Log-SPD must outperform the **ordinary covariance control**, not merely the CDE baseline, to justify a manifold-specific claim.

## 3. Validation-only probabilistic evaluation

Evaluate the best-validation checkpoint from each run using the same protocol:

- 1,256 validation dates;
- 256 generated scenarios per date;
- common sampling seed;
- inverse transformation to raw decimal excess returns;
- CRPS, Energy Score, and interval calibration.

No test observations are evaluated.

### 3.1 CDE control

In [11]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant cde \
    --run-dir /kaggle/working/phase2_cde \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:19<00:00,  3.49s/it]
CRPS: 0.00856132358999262 Energy Score: 0.0352750512684561

### 3.2 Ordinary covariance control

In [12]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant covariance \
    --run-dir /kaggle/working/phase2_covariance \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:19<00:00,  3.50s/it]
CRPS: 0.008579089448269463 Energy Score: 0.03531599537103372

### 3.3 Log-Euclidean SPD

In [13]:
!PYTHONUNBUFFERED=1 python -u scripts/evaluate_diffusion.py \
    --variant log_spd \
    --run-dir /kaggle/working/phase2_log_spd \
    --cde-run-dir /kaggle/working/phase0_cde \
    --feature-dir /kaggle/working/phase2_features \
    --batch-size 32 \
    --device cuda

Sampling: 100%|█████████████████████████████████| 40/40 [02:19<00:00,  3.50s/it]
CRPS: 0.00855422946386703 Energy Score: 0.035244180864713114

### Final comparison

In [14]:
rows = []

for name, path in (
    runs.items()
):
    with (
        path / "summary.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        train_result = json.load(
            handle
        )

    with (
        path
        / "validation_probabilistic_metrics.json"
    ).open(
        encoding="utf-8"
    ) as handle:
        eval_result = json.load(
            handle
        )

    mean_abs_ace = float(
        np.mean(
            [
                abs(
                    item[
                        "ace"
                    ]
                )
                for item in eval_result[
                    "calibration"
                ]
            ]
        )
    )

    rows.append(
        {
            "Variant": name,
            "Best epoch": train_result[
                "best_epoch"
            ],
            "Validation loss": train_result[
                "best_val_loss"
            ],
            "CRPS": eval_result[
                "crps_mean"
            ],
            "Energy Score": eval_result[
                "energy_score"
            ],
            "Mean |ACE|": (
                mean_abs_ace
            ),
        }
    )

phase2_results = (
    pd.DataFrame(
        rows
    )
    .set_index(
        "Variant"
    )
)

display(
    phase2_results
)

            Best epoch  Validation loss      CRPS  Energy Score  Mean |ACE|
Variant
CDE                 13         1.501326  0.008561      0.035275    0.186957
Covariance          13         1.492267  0.008579      0.035316    0.176673
Log-SPD             13         1.499124  0.008554      0.035244    0.183600

## 4. Phase 2A decision

Validation results from the saved execution above:

| Variant | Validation loss ↓ | CRPS ↓ | Energy Score ↓ | Mean \(|ACE|\) ↓ |
|---|---:|---:|---:|---:|
| CDE | 1.501326 | 0.008561324 | 0.035275051 | 0.186957 |
| Covariance | **1.492267** | 0.008579089 | 0.035315995 | **0.176673** |
| Log-SPD | 1.499124 | **0.008554229** | **0.035244181** | 0.183600 |

The result is mixed:

- ordinary covariance has the lowest validation diffusion loss and calibration error, but the highest CRPS and Energy Score;
- Log-SPD has the lowest CRPS and Energy Score, outperforming both CDE and the matched ordinary-covariance control on these metrics;
- Log-SPD improves diffusion loss and calibration relative to CDE, but does not beat ordinary covariance on those measures.

The previous claim that Log-SPD fails to outperform covariance on the principal probabilistic forecasting metrics does not match this saved execution. The scenario-score improvements are small and come from one seed; they do not establish a robust benefit specific to SPD geometry.

The retained reference remains **Neural CDE-conditioned diffusion**, with ordinary covariance as the matched scientific control. This comparison alone does not justify changing the retained architecture or a categorical rejection of Log-SPD.

The held-out test split remains untouched.

## Backup

Persist the canonical Phase-2A feature cache, controlled ablations, and validation-only evaluation artifacts to the central Kaggle dataset.

In [15]:
import shutil
import kagglehub

HANDLE = "amirentezari/diffusion-portfolio"

try:
    artifact_path = Path(
        kagglehub.dataset_download(
            HANDLE
        )
    )

except Exception as error:
    artifact_path = None

    print(
        "Existing backup unavailable:",
        error,
    )

staging = Path(
    "/kaggle/working/artifact_sync"
)

if staging.exists():
    shutil.rmtree(
        staging
    )

if artifact_path is not None:
    shutil.copytree(
        artifact_path,
        staging,
    )

else:
    staging.mkdir(
        parents=True,
        exist_ok=True,
    )

backups = {
    Path(
        "/kaggle/working/phase2_features"
    ): (
        staging
        / "phase2"
        / "features"
    ),

    Path(
        "/kaggle/working/phase2_cde"
    ): (
        staging
        / "phase2"
        / "cde_control"
    ),

    Path(
        "/kaggle/working/phase2_covariance"
    ): (
        staging
        / "phase2"
        / "covariance_control"
    ),

    Path(
        "/kaggle/working/phase2_log_spd"
    ): (
        staging
        / "phase2"
        / "log_spd"
    ),
}

for source, destination in (
    backups.items()
):
    if not source.exists():
        raise FileNotFoundError(
            source
        )

    if destination.exists():
        shutil.rmtree(
            destination
        )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    shutil.copytree(
        source,
        destination,
    )

    print(
        f"Prepared: {source} -> {destination}"
    )

try:
    kagglehub.dataset_upload(
        HANDLE,
        str(
            staging
        ),
        version_notes=(
            "Complete Phase 2A covariance and "
            "Log-Euclidean SPD controlled ablation"
        ),
    )

    print(
        "✅ Complete Phase 2A safely backed up"
    )

except Exception as error:
    print(
        "Backup upload skipped:",
        error,
    )

Prepared: /kaggle/working/phase2_features -> /kaggle/working/artifact_sync/phase2/features
Prepared: /kaggle/working/phase2_cde -> /kaggle/working/artifact_sync/phase2/cde_control
Prepared: /kaggle/working/phase2_covariance -> /kaggle/working/artifact_sync/phase2/covariance_control
Prepared: /kaggle/working/phase2_log_spd -> /kaggle/working/artifact_sync/phase2/log_spd
Uploading Dataset https://kaggle.com/datasets/amirentezari/diffusion-portfolio ...
More than 50 files detected, creating a zip archive...
Starting upload for file /tmp/tmpn43ctji_/archive.zip

Uploading: 100%|██████████| 533M/533M [00:05<00:00, 106MB/s]

Upload successful: /tmp/tmpn43ctji_/archive.zip (509MB)

Your dataset version has been created.
Files are being processed...
See at: https://kaggle.com/datasets/amirentezari/diffusion-portfolio
✅ Complete Phase 2A safely backed up